service-tester/src/main/java/com/adaptris/tester/runtime/Test.java, service-tester/src/main/java/com/adaptris/tester/runtime/TestList.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/TestMessage.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/TestMessageProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/metadata/InlineMetadataProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/metadata/MetadataProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/payload/FilePayloadProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/payload/InlinePayloadProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/messages/payload/PayloadProvider.java, service-tester/src/main/java/com/adaptris/tester/runtime/services/preprocessor/RemoveNodePreprocessor.java, service-tester/src/main/java/com/adaptris/tester/runtime/services/preprocessor/XpathPreprocessor.java, service-tester/src/test/java/com/adaptris/tester/runtime/services/preprocessor/XincludePreprocessorTest.java, service-tester/src/test/resources/log4j2.xml
Various Fixes and Improvements:
-  TestMessages payload can now be a file
-  Xpath Preprocessors support namespaces
-  Move log4j2.xml to test configuration
=> [service-tester] Messages from file, Namespaces in Xpath Process, and log4j change

adapter/src/main/java/com/adaptris/core/runtime/AdapterRegistry.java, ivy/build.gradle, ivy/ivy-adapter.xml
This replaces the outdated FastClasspathScanner with its successor ClassGraph, which is more reliable and future-proof, as reported in #19.
I've run `ant test`, but after running for about an hour and a half, the tests are still not complete (StandardHTTPProducerTest took 1,732 seconds!), so I've decided to just submit this as-is.
=> Replace outdated FastClasspathScanner with ClassGraph

interlok-core/src/main/java/com/adaptris/core/services/exception/ExceptionAsXml.java, interlok-core/src/main/java/com/adaptris/core/services/exception/ExceptionReport.java, interlok-core/src/main/java/com/adaptris/core/services/exception/ExceptionReportGenerator.java, interlok-core/src/main/java/com/adaptris/core/services/exception/SimpleExceptionReport.java, interlok-core/src/main/java/com/adaptris/core/services/exception/XmlExceptionReport.java, interlok-core/src/main/java/com/adaptris/core/services/exception/XmlReportWithStacktrace.java, interlok-core/src/test/java/com/adaptris/core/services/exception/XmlExceptionReportTest.java
- Change the create() interface method (which is a breaking change).
- Create a new ExceptionReport object with an asMap() method so that it could be reused later by ExceptionAsJson et. al.
- XML uses XStream, which has the side effect of serializing the stacktrace as <trace>...
- Should we deprecate "SimpleExceptionReport"?
(run the tests, check standard-error output from ExceptionReportTest, to see the XML).
=> INTERLOK-2625 Add XmlExceptionReport / XmlExceptionWithStacktrace

interlok-core/src/main/java/com/adaptris/core/transform/XmlSchemaValidator.java, interlok-core/src/test/java/com/adaptris/core/transform/XmlValidationServiceTest.java
- Schema is not created until first use, and then cached which means we needed to change some of the tests.
- Deprecate schema-metadata-key and make schema %message{}
- Add protection for if people have configured c:/x/y/z as their schema via FsHelper (it wouldn't have worked anyway, but now it could...)
=> INTERLOK-2668 - Add Cache to SchemaValidator

interlok-core/src/main/java/com/adaptris/core/services/jdbc/NoParameterLogging.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/ParameterLogger.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/StatementParameter.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/StatementParameterImpl.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/TruncatedParameterLogger.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/TypedStatementParameter.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/ParameterLoggerTest.java
- Add ParameterLogger function interface.
- Default behaviour is to log the toString() on the object which was
the existing behaviour.
- Added a TruncatedParameterLogger and NoParamterLogging version.
- Add tests.
=> INTERLOK-2675 add ParameterLogger interface.

interlok-core/src/main/java/com/adaptris/core/fs/FsConsumer.java, interlok-core/src/main/java/com/adaptris/core/fs/FsHelper.java, interlok-core/src/main/java/com/adaptris/core/services/ReadFileService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/ReadMetadataFromFilesystem.java, interlok-core/src/test/java/com/adaptris/core/fs/FsHelperTest.java, interlok-core/src/test/java/com/adaptris/core/services/ReadFileServiceTest.java, interlok-core/src/test/java/com/adaptris/core/stubs/TempFileUtils.java
Support strings are now
* %message{metadata-key}
* file:///c:/blah/blah/blah
* c:/blah/blah/blah
The second makes it consistent with message-driven-destination.
=> INTERLOK-2681 Make read-file-service support URLs

interlok-core/src/main/java/com/adaptris/core/PoolingWorkflow.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/ServiceWorkerPool.java
- According to the javadocs, SoftMinEvictable means that it will
only evict if there are already min-idle instances available. This
is the more appropriate check rather than MinEvictable
=> INTERLOK-2687 Switch to using setSoftMinEvictableTimeMillis

interlok-core/src/main/java/com/adaptris/core/services/dynamic/DefaultServiceExtractor.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/DynamicServiceExecutor.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ExtractorWithConnection.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/MimeServiceExtractor.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ServiceExtractor.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ServiceExtractorImpl.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ServiceFromDataInputParameter.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ServiceFromUrl.java
- Added a `getService(AdaptrisMessage, AdaptrisMarshaller)` method; it is a default interface method with appropriate javadocs saying how you should just extend ServiceExtractorImpl if you can't be bothered
to change your impl.
- Added ServiceExtractorImpl
- DefaultServiceExtractor doesn't extend it, so we get coverage...
- Switch DynamicServiceExecutor to use the new method.
Tests still pass with no changes (and still give 100% 👍 ).
=> INTERLOK-2707 Modify ServiceExtractor Interface to return a Service

interlok-core/src/test/java/com/adaptris/core/PortManager.java, interlok-core/src/test/java/com/adaptris/core/jmx/JmxNotificationConsumerTest.java, interlok-core/src/test/java/com/adaptris/security/Config.java, interlok-core/src/test/java/com/adaptris/security/SingleEntryKeystoreBase.java, interlok-core/src/test/java/com/adaptris/security/TestCertificateGeneration.java, interlok-core/src/test/java/com/adaptris/security/TestCertificateHandler.java, interlok-core/src/test/java/com/adaptris/security/TestCompositeKeystore.java, interlok-core/src/test/java/com/adaptris/security/TestConfiguredUrl.java, interlok-core/src/test/java/com/adaptris/security/TestDefaultSecurityService.java, interlok-core/src/test/java/com/adaptris/security/TestInlineKeystore.java, interlok-core/src/test/java/com/adaptris/security/TestKeyStore.java, interlok-core/src/test/java/com/adaptris/security/TestKeyStoreInfoChange.java, interlok-core/src/test/java/com/adaptris/security/TestKeystoreLocation.java, interlok-core/src/test/java/com/adaptris/security/TestPassword.java, interlok-core/src/test/java/com/adaptris/security/TestSecurityUtil.java, interlok-core/src/test/java/com/adaptris/security/TestSingleX509Keystore.java, interlok-core/src/test/resources/security-test.properties.template
- Reviewed the tests, made classes annotation based.
- Switch out clogger for slf4j
- TestCompositeKeystore now uses a unique keystore rather than
the same keystore every test...
=> INTERLOK-2472 Make TestCompositeKeystore use a unique keystore

interlok-common/src/main/java/com/adaptris/interlok/types/InterlokMessage.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataDataOutputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamInputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamOutputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamParameter.java, interlok-core/src/main/java/com/adaptris/core/common/PayloadStreamOutputParameter.java, interlok-core/src/main/java/com/adaptris/core/security/SymmetricKeyCryptographyService.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/ServiceWorkerPool.java, interlok-core/src/test/java/com/adaptris/core/common/MetadataStreamDataInputParameterTest.java, interlok-core/src/test/java/com/adaptris/core/common/MetadataStreamDataOutputParameterTest.java, interlok-core/src/test/java/com/adaptris/core/common/PayloadStreamInputParameterTest.java, interlok-core/src/test/java/com/adaptris/core/common/PayloadStreamOutputParameterTest.java, interlok-core/src/test/java/com/adaptris/core/security/SecurityServiceExample.java, interlok-core/src/test/java/com/adaptris/core/security/SymmetricKeyCryptographyServiceTest.java
- Add a MessageWrapper interface to InterlokMessage
- Add a MetadataStreamInputParameter which gives us a metadata value as a stream.
- Add additional docs for each of the setters alg/vector/cipher
- Made Payload/Metadata outputs implement MessageWrapper.
- Could be used to support INTERLOK-2762 with the intention that we might do something like  (since TypedAdaptrisMessage would implement AdaptrisMessage but provide improved resolution capabilities).
```
TypedAdaptrisMessage eMsg = msg.wrap(new TypedWrapper());
for (Service s : services) {
s.doService(eMsg);
}
```
=> Feature/interlok 2790 - make symmetricKeyCrypto work with metadata as well as payload

interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyRouteSpec.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/JettyRouteSpecTest.java
- Check groupCount size against the number of keys configured
and throw exception if count>keys. If there are too many
keys for the match group then we just have unset metadata;
- Add a specific JettyRouteSpecTest for coverage
=> INTERLOK-2753 Check groupCount vs metadata size

interlok-core/src/main/java/com/adaptris/core/MessageLoggerImpl.java, interlok-core/src/main/java/com/adaptris/core/MetadataCollection.java, interlok-core/src/main/java/com/adaptris/core/metadata/DiscardValuesTooLongFilter.java, interlok-core/src/main/java/com/adaptris/core/metadata/PasswordMetadataFilter.java, interlok-core/src/main/java/com/adaptris/core/metadata/RegexMetadataFilter.java, interlok-core/src/main/java/com/adaptris/core/util/MetadataKeysOnly.java
MessageLogger - AIOOB exception trace
Made thread safe by replacing parallelStream with stream.
=> Thread safe replaced parallelStream with stream in MessageLoggerImpl.

interlok-core/src/main/java/com/adaptris/core/services/jdbc/JdbcMapInsert.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/JdbcMapUpsert.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/JdbcMapInsertCase.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/JdbcMapInsertTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/JdbcMapUpsertTest.java
- Change method signature to return int
- add helper method to add the metadata if configured.
- this change doesn't have any impact in intelrok-core; but it will have downstream impact on interlok-csv / interlok-json etc.
=> INTERLOK-2759 Change method signature to return an int.

interlok-core/src/main/java/com/adaptris/core/metadata/FixedValuesMetadataFilter.java, interlok-core/src/main/java/com/adaptris/core/services/aggregator/IgnoreOriginalMimeAggregator.java, interlok-core/src/main/java/com/adaptris/core/services/aggregator/MimeAggregator.java, interlok-core/src/main/java/com/adaptris/util/text/mime/MultiPartOutput.java, interlok-core/src/test/java/com/adaptris/core/metadata/FixedValuesMetadataFilterTest.java, interlok-core/src/test/java/com/adaptris/core/services/aggregator/MimeAggregatorCase.java, interlok-core/src/test/java/com/adaptris/core/services/aggregator/MimeAggregatorTest.java
- Introduce new part-content-id and part-content-type expressions
- Deprecate metadata-key variants
- Add part-header-filter which adds headers for each nested part
- Add mime-header-filter which adds headers to the top level.
- Tests; 100% on MimeAggregator
- Fix bug with MultipartOutput; which was probably introduced when we added support for large message mime-encoding...
- Add a FixedValueMetadataFilter which means we can hard-code metadata elements (much like add-metadata-service) where a metadata-filter is used. Since we don't always have access to the 'message' we can't make this filter resolve metadata via the expression language.
```
Message-ID: 8d00402b-59bf-4fd1-b98a-581c80b54ef0
Mime-Version: 1.0
Content-Type: multipart/form-data; …
```
=> INTERLOK-2833 Add arbitrary headers to nested mime-parts

interlok-core/src/main/java/com/adaptris/core/DefaultAdaptrisMessageImp.java, interlok-core/src/main/java/com/adaptris/core/common/ByteArrayFromMetadata.java, interlok-core/src/main/java/com/adaptris/core/common/ByteArrayFromMetadataWrapper.java, interlok-core/src/main/java/com/adaptris/core/common/ByteArrayFromObjectMetadata.java, interlok-core/src/main/java/com/adaptris/core/common/ByteArrayFromPayload.java, interlok-core/src/main/java/com/adaptris/core/services/mime/InlineMimePartBuilder.java, interlok-core/src/main/java/com/adaptris/core/services/mime/MimePartBuilder.java, interlok-core/src/main/java/com/adaptris/core/services/mime/MultipartMessageBuilder.java, interlok-core/src/main/java/com/adaptris/util/text/mime/MimeUtils.java, interlok-core/src/test/java/com/adaptris/core/common/ByteArrayFromPayloadTest.java, interlok-core/src/test/java/com/adaptris/core/common/ByteArrayMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/common/ByteArrayObjectMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/mime/FlattenMimePartTest.java, interlok-core/src/test/java/com/adaptris/core/services/mime/MimePartBuilderTest.java, interlok-core/src/test/java/com/adaptris/core/services/mime/MimePartChooserTest.java, interlok-core/src/test/java/com/adaptris/core/services/mime/MultipartMessageBuilderTest.java
Added supporting ByteArray message wrapper implementations.
Add MultipartMessageBuilder which supports
- Arbitrary headers at the top level via mime-header-filter
- Custom expression based Content-ID
Nested parts are created using inline-mime-part-builder (working off byte-arrays) these support
- Expression based Content-ID + Content-Type + Content-Transfer-Encoding
- Arbitrary headers built from metadata for each part.
=> INTERLOK-2834 Add MultipartMessageBuilder

interlok-core/src/main/java/com/adaptris/core/http/RequestParameterConverterService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/CreateQueryStringFromMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/FormDataFromMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/FormDataToMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/UrlEncodedMetadataValues.java, interlok-core/src/test/java/com/adaptris/core/http/RequestParameterConverterServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/CreateQueryStringFromMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/FormDataFromMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/FormDataToMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/stubs/DefectiveAdaptrisMessage.java, interlok-core/src/test/java/com/adaptris/core/stubs/DefectiveMessageFactory.java
- Deprecate RequestParameterConverter service for a FormDataToMetadata
- Add a FormDataFromMetadata
- Parameters on the URI will be handled by a ParameterHandler...
- Add a hierarchy to encode a filtered set of metadata.
- Add additional break when using metadata to DefectiveMessageFactory
=> INTERLOK-2840 Add www-form-url-encded to/from metadata.

interlok-core/src/main/java/com/adaptris/core/AdapterXStreamMarshallerFactory.java, interlok-core/src/main/java/com/adaptris/core/marshaller/xstream/PrettyStaxDriver.java, interlok-core/src/test/java/com/adaptris/core/marshaller/xstream/PrettyStaxDriverTest.java
- Make PrettyStaxDriver extend StandardStaxDriver so that we use the JVM internal Stax implementation.
- Make it controllable via the system property "interlok.xstream.jdk.stax" which defaults to true.
- Add tests (apart from the no-args constructor) to make sure we get the desired behaviours.
=> INTERLOK-2865 Extend StandardDriver not StaxDriver

interlok-core/src/main/java/com/adaptris/core/services/conditional/DoWhile.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/MaxLoopBehaviour.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/OnMaxNoOp.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/OnMaxStopProcessing.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/OnMaxThrowException.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/While.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/DoWhileTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/MaxLoopBehaviourTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/WhileTest.java
- Implementations are "no-op", "throw-exception", "add-stop-processing" flags.
- behaviour is marked as advanced config.
More builder methods that use unchecked things :)
=> INTERLOK-2846 Add on-max behaviour.

interlok-core/src/main/java/com/adaptris/core/AdaptrisMessage.java, interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageImp.java, interlok-core/src/main/java/com/adaptris/core/DefaultAdaptrisMessageImp.java, interlok-core/src/main/java/com/adaptris/core/lms/FileBackedMessageImpl.java, interlok-core/src/main/java/com/adaptris/core/services/ChangeCharEncodingService.java, interlok-core/src/test/java/com/adaptris/core/AdaptrisMessageCase.java, interlok-core/src/test/java/com/adaptris/core/services/ChangeCharEncodingServiceTest.java
- Execute Charset.forName() if charEnc != null which will throw a RuntimeException.
- Side effect is that the name is always the formal name (i.e.utf-8 => UTF-8).
- Made all the deprecated methods in AdaptrisMessage default to avoid code duplication.
- Fixed ChangeCharEncodingTest to use the formal name (since a string compare iso-8859-1 != ISO-8859-1)...
=> INTERLOK-2848 Check character set is valid

interlok-core/src/main/java/com/adaptris/core/AdaptrisConnectionImp.java, interlok-core/src/main/java/com/adaptris/core/JndiBindable.java, interlok-core/src/main/java/com/adaptris/core/ServiceCollectionImp.java, interlok-core/src/main/java/com/adaptris/core/ServiceImp.java, interlok-core/src/main/java/com/adaptris/core/SharedConnection.java, interlok-core/src/main/java/com/adaptris/core/util/JndiHelper.java, interlok-core/src/test/java/com/adaptris/core/JndiContextFactoryTest.java, interlok-core/src/test/java/com/adaptris/core/ServiceCase.java, interlok-core/src/test/java/com/adaptris/core/SharedComponentListTest.java, interlok-core/src/test/java/com/adaptris/core/transaction/DummyTransactionManager.java, interlok-core/src/test/java/com/adaptris/core/util/JndiHelperTest.java
- ServiceImp#lookupName annotated with removal+deprecation
- ServiceCollectionImp#lookupName annotated with removal+deprecation
- AdaptrisConnectionImp#lookupName annotated with removal+deprecation
Since SharedService / SharedConnection implement Service & Connection directly there isn't any jiggery pokery around parent classes.
=> INTERLOK-2872 Deprecated JndiBindable#getLookupName

interlok-core/src/main/java/com/adaptris/core/http/jetty/HashLoginServiceFactory.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JdbcLoginServiceFactory.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyLoginServiceFactory.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/LoginServiceFactoryImpl.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/HttpConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/LoginServiceFactoryTest.java
- Since both JDBCLoginService and HashLoginService have the same configuration; make an abstract class with generics.
- Add a JDBCLoginService variant; reusing LoginServiceProxy from INTERLOK-2799
- Add unit tests checking behaviour only.
=> INTERLOK-2721 Added JdbcLoginServiceFactory

interlok-core/src/main/java/com/adaptris/core/XpathProduceDestination.java, interlok-core/src/main/java/com/adaptris/core/jdbc/JdbcXPathParameter.java, interlok-core/src/main/java/com/adaptris/core/services/aggregator/XmlDocumentAggregator.java, interlok-core/src/main/java/com/adaptris/core/services/exception/ExceptionAsXml.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/JdbcDataQueryService.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/JdbcIteratingDataCaptureServiceImpl.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/SplittingXmlPayloadTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/XmlPayloadTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/XpathMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/XpathObjectMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/path/XPathService.java, interlok-core/src/main/java/com/adaptris/core/services/routing/XmlSyntaxIdentifierImpl.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/XpathDocumentCopier.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/XpathMessageSplitter.java, interlok-core/src/main/java/com/adaptris/core/transform/XmlBasicValidator.java, interlok-core/src/main/java/com/adaptris/core/transform/XmlRuleValidator.java, interlok-core/src/main/java/com/adaptris/core/util/DocumentBuilderFactoryBuilder.java, interlok-core/src/main/java/com/adaptris/core/util/XmlHelper.java, interlok-core/src/main/java/com/adaptris/util/text/xml/MappedResolver.java, interlok-core/src/main/java/com/adaptris/util/text/xml/Resolver.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XmlTransformer.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XmlTransformerFactoryImpl.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XpathMergeImpl.java, interlok-core/src/test/java/com/adaptris/core/XpathProduceDestinationTest.java, interlok-core/src/test/java/com/adaptris/core/jmx/JmxConnectionTest.java, interlok-core/src/test/java/com/adaptris/core/util/DocumentBuilderFactoryBuilderTest.java, interlok-core/src/test/java/com/adaptris/core/util/XmlHelperTest.java
- Make sure that creation of XmlUtils uses the entity from the builder; This has the side effect of having no caching Resolver; however this is acceptable since most of the time the XmlUtils class is gc'd so
the caching is somewhat pointless.
- Improve logging in the Resolvers
- Deprecated newInstance() methods in DocumentBuilderFactoryBuilder since they are really poorly named!
=> INTERLOK-2901 Ensure XmlHelper+XmlTransform configure the builder properly

interlok-common/src/main/java/com/adaptris/core/management/webserver/JettyServerManager.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/HashLoginServiceFactory.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JdbcLoginServiceFactory.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/LoginServiceFactoryImpl.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/LoginServiceFactoryTest.java
- Add file verification using FsWorker.checkReadable() when create the actual login services.
- Add a system property that controls whether or not we call setThrowUnavailableOnStartupException on the webapp context
=> INTERLOK-2902 Add file on the login-service-factory

interlok-core-apt/src/main/java/com/adaptris/annotation/AdvancedConfig.java, interlok-core/src/main/java/com/adaptris/core/Adapter.java, interlok-core/src/main/java/com/adaptris/core/AdaptrisConnectionImp.java, interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageWorkerImp.java, interlok-core/src/main/java/com/adaptris/core/QuartzCronPoller.java, interlok-core/src/main/java/com/adaptris/core/ServiceCollectionImp.java, interlok-core/src/main/java/com/adaptris/core/ServiceImp.java, interlok-core/src/main/java/com/adaptris/core/SharedServiceImpl.java, interlok-core/src/main/java/com/adaptris/core/StandaloneConsumer.java, interlok-core/src/main/java/com/adaptris/core/WorkflowImp.java, interlok-core/src/main/java/com/adaptris/core/fs/FsConsumer.java, interlok-core/src/main/java/com/adaptris/core/fs/FsImmediateEventPoller.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpConsumer.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpProducer.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyAsyncWorkflowInterceptor.java
- Mark channel-wait-unavailable as rare in workflowImp
- Mark is-tracking-endpoint as rare in services.
- Mark startupEventImp / heartbeatEventImp as rare in Adapter
- Mark wipSuffix as rare in Fs / FtpConsumer
- Mark cacheKey as rare in JettyAsyncInterceptor
- Mark useCustomThreadPool as rare in QuartzCronPoller
This should cover at least one of each of the main types of object that have dedicated settings
=> INTERLOK-2663 Add rare as an attribute to AdvancedConfig

interlok-core/src/main/java/com/adaptris/core/jms/jndi/SimpleFactoryConfiguration.java, interlok-core/src/main/java/com/adaptris/util/SimpleBeanUtil.java, interlok-core/src/test/java/com/adaptris/core/jms/jndi/SimpleFactoryConfigurationTest.java, interlok-core/src/test/java/com/adaptris/util/SimpleBeanUtilTest.java
- Modify tests that explicitly tested for non-convertable values since SimpleBeanUtil handles that silently.
- Use BooleanUtils.or() to avoid branch coverage testing requirements.
- Made SimpleBeanUtils have a functional interface since this is what is intended.
=> INTERLOK-2943 Refactor to use SimpleBeanUtil

interlok-core/src/main/java/com/adaptris/core/services/cache/AddValueToCache.java, interlok-core/src/main/java/com/adaptris/core/services/cache/CacheEntryEvaluator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/CacheKeyTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/CacheServiceBase.java, interlok-core/src/main/java/com/adaptris/core/services/cache/CacheServiceImpl.java, interlok-core/src/main/java/com/adaptris/core/services/cache/CacheValueTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/GetValueFromCache.java, interlok-core/src/main/java/com/adaptris/core/services/cache/RemoveKeyFromCache.java, interlok-core/src/main/java/com/adaptris/core/services/cache/SingleKeyCacheService.java, interlok-core/src/main/java/com/adaptris/core/services/cache/SingleKeyValueCacheImpl.java, interlok-core/src/main/java/com/adaptris/core/services/cache/translators/BytePayloadCacheValueTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/translators/StaticCacheValueTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/translators/StringPayloadCacheTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/cache/translators/XpathCacheValueTranslator.java, interlok-core/src/test/java/com/adaptris/core/services/cache/AddValueToCacheTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/CacheServiceExample.java, interlok-core/src/test/java/com/adaptris/core/services/cache/CheckAndRetrieveCacheTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/CheckCacheServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/GetValueFromCacheTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/RemoveKeyFromCacheTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/SingleKeyCacheCase.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/BytePayloadCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/CacheValueTranslatorBaseCase.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/JmsReplyToCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/MetadataCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/ObjectMetadataCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/StaticCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/StringPayloadCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/translators/XpathCacheValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/stubs/DefectiveAdaptrisMessage.java
Hierarchy change to existing services for re-use.
- AddValueToCache which adds a single value to the cache
- RemoveKeyFromCache which removes a single key from the cache without retrieving it.
- GetValueFromCache allows you to retrieve a single value from the cache (with exception-if-not-found support).
- There is no "check-cache" since this can be done with the exists-in-cache condition (since we want to discourage branching-service-collection).
- 100% coverage on translators; 
- remove the cache wrapper from CacheServiceBase which was used to wrap the deprecated cache (up until 3.9.0)
- Added some additional methods for DefectiveMessage.
Looks like : 
```xml
<add-single-value-to-cache>
<connection class="cache-connection"/>
<key>%message{%uniqueId}</key>
<value-translator …
```
=> INTERLOK-2965 simplified cache services

interlok-core/src/main/java/com/adaptris/core/services/cache/CacheEntryEvaluator.java, interlok-core/src/test/java/com/adaptris/core/services/cache/CacheEntryEvaluatorTest.java
If we have configured a remove-from-cache; then we might be in a situation where we call valueTranslator.addValueToMessage(). In this case, because of the functional interface + default method change we will throw an exception, but the user may explicitly have configured no value-translator since they don't want to retrieve the value...
i.e. if we configure this : 
```
<remove-from-cache>
<unique-id>remove-request-from-cache</unique-id>
<connection class="shared-connection">
<lookup-name>request-cache</lookup-name>
</connection>
<cache-entry-evaluator>
<key-translator class="static-cache-value-translator">
<value>%message{%uniqueId}</value>
</key-translator>
</cache-entry-evaluator>
</remove-from-cache>
```
Then we get an exception; but we really shouldn't.
=> INTERLOK-2965 - Make sure we have a null value translator as default

interlok-common/build.gradle, interlok-core/build.gradle, interlok-core/src/test/java/com/adaptris/core/http/jetty/ServletWrapperTest.java
This reverts commit 3126b22b7f674f1769b3560cbe7698606c97763d.
I'm reverting jetty to 9.4.20.v20190813 as 9.4.21.v20190926 is not working well with Shiro in the UI.
At least until we find a good fix or either Shiro or Jetty fix the issue.
The UI start ok but as soon as we request an html page we get a:
`javax.servlet.ServletException: javax.servlet.ServletException: java.lang.ClassCastException: org.apache.shiro.web.servlet.ShiroHttpServletRequest cannot be cast to org.eclipse.jetty.server.Request
at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:162)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle (Server.java:500)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1 …
=> Revert "Bump jetty to 9.4.21"

interlok-common/src/main/java/com/adaptris/interlok/cloud/RemoteBlobFilter.java, interlok-common/src/main/java/com/adaptris/interlok/cloud/RemoteBlobFilterWrapper.java, interlok-common/src/main/java/com/adaptris/interlok/cloud/RemoteFile.java, interlok-common/src/main/java/com/adaptris/interlok/util/Args.java, interlok-common/src/main/java/com/adaptris/interlok/util/package-info.java, interlok-common/src/test/java/com/adaptris/interlok/cloud/RemoteBlobFilterWrapperTest.java, interlok-common/src/test/java/com/adaptris/interlok/util/ArgsTest.java, interlok-core/src/main/java/com/adaptris/core/util/Args.java
- Add RemoteBlobFilter and RemoteBlobFilterWrapper which wraps a FileFilter (for easy filtering).
- Moved com.adaptris.core.util.Args into com.adaptris.interlok.util however, not deprecating it because of excessive use, but we have to consider what happens in 4.0 since interlok-common probably shouldn't exist as a sub-project.
=> INTERLOK-2860 Add RemoteBlobFilter and implementation

interlok-core/src/main/java/com/adaptris/core/jms/FailoverJmsConnection.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsConnection.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsPollingConsumerImpl.java, interlok-core/src/main/java/com/adaptris/core/jms/VendorImplementation.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsConsumerTest.java
- Add a default createConnection() method to VendorImplementation which is appropriate for JMS1.1
- Concrete Imps (like OracleAQ) can override it as required.
- Make sure we call the new vendor-imp method in the connection / polling consumer.
- Fix JmsConsumer mock test
Am not entirely happy with all the instance variables being used by JmsConnection (it seems a bit lame).
=> INTERLOK-2972 - Add createConnection() method to VendorImplementation

interlok-core/src/main/java/com/adaptris/core/CoreConstants.java, interlok-core/src/main/java/com/adaptris/core/PoolingWorkflow.java, interlok-core/src/main/java/com/adaptris/core/StandardWorkflow.java, interlok-core/src/main/java/com/adaptris/core/WorkflowImp.java, interlok-core/src/main/java/com/adaptris/core/WorkflowInterceptor.java, interlok-core/src/main/java/com/adaptris/core/interceptor/LoggingContextWorkflowInterceptor.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsConstants.java, interlok-core/src/main/java/com/adaptris/core/jms/MetadataHandler.java, interlok-core/src/test/java/com/adaptris/core/interceptor/LoggingContextInterceptorTest.java
This can be used in combination with an appropriate logging Appender to log message id and such to ElasticSearch for better tracing of a message.
=> Allow adding workflow, channel, messageid and any other message data to MDC

interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyRouteSpec.java
Since we default metadata-keys in jettyRouteSpec to be an empty list of strings; this is shown by the UI, since it's not null
- In the situation of a new route spec being created by the UI, it needs to default to null, so it's never shown.
- In the situation where it's already been configured, it's fine to show it, because it's been explicitly configured
=> INTERLOK-3030 Default metadata-keys in JettyRouteSpec to null

interlok-core/src/main/java/com/adaptris/core/fs/CompositeFileFilter.java, interlok-core/src/test/java/com/adaptris/core/fs/CompositeFileFilterTest.java
- Wherever we just log the exception; now throw a RuntimeException
- Modify the tests to cope with the new exceptions.
=> INTERLOK-3025 Throw RTE when we fail to create a filter.

build.gradle, interlok-core/src/main/java/com/adaptris/core/management/VersionReport.java, interlok-core/src/test/java/com/adaptris/core/management/VersionReportTest.java
- Remove XStreamAlias since it never had a public constructor, it was not usable
- Add build.info support when generating the version,
- Use chomp() to remove the last linefeed
- Refactor VersionReport for testability.
- Add tests for 100% coverage.
Merge target is post 3.9.2
=> INTERLOK-3008 Add build.info into version report

interlok-core/src/main/java/com/adaptris/core/StandaloneRequestor.java, interlok-core/src/test/java/com/adaptris/core/StandaloneRequestorTest.java
Add null checks for messages and a unit test that confirmed the bug and then the fix.
=> INTERLOK-2829 Add null checks and unit test

interlok-core/src/main/java/com/adaptris/core/ftp/AggregatingFtpConsumer.java
Just fixed a typo for the property deleteAggregatedFiles in @DisplayOrder annotation.
=> Fix typo for deleteAggregatedFiles in @DisplayOrder

build.gradle, interlok-common/build.gradle, interlok-core/build.gradle, interlok-core/src/main/java/com/adaptris/core/jms/JmsConsumer.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsAsyncProducerTest.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsConsumerTest.java
One of the changes between v1 and later versions or Mockito is the handling of null values when setting expectations or verifying behaviour - ````any(…)```` used to be fine with null but not any more. Either ````eq(null)```` or ````any()```` need to be used instead.
=> INTERLOK-2904 Upgrade to mockito 3.x

interlok-common/src/main/java/com/adaptris/interlok/cloud/RemoteBlobFilterWrapper.java, interlok-common/src/main/java/com/adaptris/interlok/util/FileFilterBuilder.java, interlok-common/src/test/java/com/adaptris/interlok/util/FileFilterBuilderTest.java, interlok-core/src/main/java/com/adaptris/core/fs/FsHelper.java
- Add FileFilterBuilder to create the FileFilter instances.
- Switch FsHelper to use the new builder.
=> INTERLOK-3003 Add support for primitives in FileFilter constructors

build.gradle, gradle/owasp-exclude.xml
Add owasp dependency checker
```
./gradlew dependencyCheckAnalyze
```
Which will give 0 vulns; because I have included a suppression file for the activemq-client CVE vulns; and also skipped the "antSql" configuration to avoid mysql CVE vulns.
But the interesting thing is that since the suppression file can be a URL -> we can actually say 
```
dependencyCheck  {
suppressionFiles= [ "https://raw.githubusercontent.com/adaptris/interlok/develop/gradle/owasp-exclude.xml" ]
}
```
In all the downstream projects... and maintain a single master in interlok itself.
=> Add owasp dependency check.

interlok-core/src/main/java/com/adaptris/core/CloneMessageServiceList.java, interlok-core/src/test/java/com/adaptris/core/CloneMessageServiceListTest.java
- Deprecate override-metadata member.
-- In deprecated mode; the default is "NoOpMetadataFilter" for backwards compat.
- If metadata filter is configured; we just use that and set the default to be RemoveAllMetadata
=> INTERLOK-3163 Deprecate override-metadata

interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageImp.java, interlok-core/src/test/java/com/adaptris/core/AdaptrisMessageCase.java
Noticed that the ticket has a comment that suggests getting the payload through “%payload”, so add that capability.
=> INTERLOK-2761 Allow %message{%payload} to resolve entire payload

interlok-core/src/main/java/com/adaptris/core/util/PayloadMessageLogger.java, interlok-core/src/test/java/com/adaptris/core/util/MessageLoggerTest.java
Add option that allows the payload message logger to only log the payload, excluding metadata (which remains the default).
=> INTERLOK-3143 Allow payload-only message logging

interlok-core/src/main/java/com/adaptris/core/common/ByteArrayPayloadDataOutputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MultiPayloadByteArrayOutputParameter.java, interlok-core/src/test/java/com/adaptris/core/common/ByteArrayPayloadDataOutputParameterTest.java
Add new byte[] output parameter that the multi-payload byte[] output parameter can extend.
=> INTERLOK-3167 Add new byte[] output parameter

docs/adr/0006-workflow-callback.md, interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageListener.java, interlok-core/src/main/java/com/adaptris/core/CoreConstants.java, interlok-core/src/main/java/com/adaptris/core/FailedMessageRetrierImp.java, interlok-core/src/main/java/com/adaptris/core/ListenerCallbackHelper.java, interlok-core/src/main/java/com/adaptris/core/MultiProducerWorkflow.java, interlok-core/src/main/java/com/adaptris/core/NoRetries.java, interlok-core/src/main/java/com/adaptris/core/PoolingWorkflow.java, interlok-core/src/main/java/com/adaptris/core/RootProcessingExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/StandardWorkflow.java, interlok-core/src/main/java/com/adaptris/core/lms/LargeMessageWorkflow.java, interlok-core/src/test/java/com/adaptris/core/PoolingWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/StandardWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/stubs/MockMessageListener.java
- Interface changed to `onAdaptrisMessage(AdaptrisMessage, Consumer<AdaptrisMessage> onSuccess)`, onFailure is not considered in scope for this PR since it adds too much complexity (we need to handle properly in v4).
- Add a helper class to handle the callbacks
- Modify workflows to call successCallback
Tests aren't broken (which is good); but anything with Workflows will be broken
- profiler (if it only profiles onAdaptrisMessage() )
- interlok-client (maybe)
- vertx
=> INTERLOK-3056 AdaptrisMessageListener callback

interlok-core/src/main/java/com/adaptris/core/StandardWorkflow.java, interlok-core/src/main/java/com/adaptris/core/StandardWorkflowImpl.java
Move protected methods out of StandardWorkflow into StandardWorkflowImp which means that you can get all the behavioural characteristics of
StandardWorkflow w/o having to override the synchronised onAM (which code analyzers don't like).
=> INTERLOK-3010 Move protected methods out of StandardWorkflow

interlok-common/build.gradle, interlok-core/build.gradle, interlok-core/src/main/java/com/adaptris/core/runtime/WorkflowManager.java, interlok-core/src/test/java/com/adaptris/core/runtime/RetryMessageErrorHandlerMonitorTest.java
- Anything that depends on beanutils will pull in commons-collections3 however we don't explicitly depend on it any longer.
=> INTERLOK-2858 Switch to cmmons-collections4

interlok-core/src/main/java/com/adaptris/core/services/Base64DecodeService.java, interlok-core/src/main/java/com/adaptris/core/services/Base64EncodeService.java, interlok-core/src/main/java/com/adaptris/core/services/Base64Service.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/Base64DecodeMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/Base64EncodeMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/Base64MetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/MetadataToPayloadService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadToMetadataService.java, interlok-core/src/main/java/com/adaptris/core/util/EncodingHelper.java, interlok-core/src/main/java/com/adaptris/util/text/Base64ByteTranslator.java, interlok-core/src/main/java/com/adaptris/util/text/Conversion.java, interlok-core/src/test/java/com/adaptris/core/security/SymmetricKeyCryptographyServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/Base64ServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/MetadataStatementCreatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/Base64MetadataDecodeTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/MetadataToPayloadTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/PayloadToMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/SplitJoinServiceFilterTest.java, interlok-core/src/test/java/com/adaptris/core/util/EncodingHelperTest.java, interlok-core/src/test/java/com/adaptris/util/text/ByteTranslatorTest.java, interlok-core/src/test/java/com/adaptris/util/text/ConversionTest.java
- Add EncodingHelper that wraps the various MimeUtility / Base64 wrappers.
- EncodingHelper also wraps an enum for the Base64 style
- Deprecate Conversion#base64 operations
- Base64ByteTranslator now uses java.util.Base64
- MetadataToPayload / PayloadToMetadata switched to use EncodingHelper.Encoding enum
- Base64Encode / Decode / EncodeMetadata / DecodeMetadata now uses one of the Base64 styles.
It's arguable that Conversion#base64 methods should just delegate to Base64.getEncoder/getDecoder so happy to do that to avoid lots of deprecation warnings...
=> INTERLOK-3170 Switch to using java.util.Base64

interlok-core/src/main/java/com/adaptris/core/services/routing/AlwaysMatchSyntaxIdentifier.java, interlok-core/src/main/java/com/adaptris/core/services/routing/RegexpSyntaxIdentifier.java, interlok-core/src/main/java/com/adaptris/core/services/routing/SyntaxIdentifier.java, interlok-core/src/main/java/com/adaptris/core/services/routing/SyntaxIdentifierBase.java, interlok-core/src/main/java/com/adaptris/core/services/routing/SyntaxIdentifierImpl.java, interlok-core/src/main/java/com/adaptris/core/services/routing/XpathNodeIdentifier.java, interlok-core/src/main/java/com/adaptris/core/services/routing/XpathSyntaxIdentifier.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/IfElseTest.java, interlok-core/src/test/java/com/adaptris/core/services/routing/RegexpSyntaxIdentifierTest.java, interlok-core/src/test/java/com/adaptris/core/services/routing/SyntaxIdentifierCase.java
- Remove patterns from the SyntaxIdentifier interface
- Restructured the hierarchy so there's an extra SyntaxBase to add Destination
- AlwaysMatch just extends SyntaxBase, others extend SyntaxImp as they still need patterns
- Add explicit test into IfElse to test syntax identifiers as conditions.
=> INTERLOK-3111 Made SyntaxIdentifier extend Condition

interlok-core/build.gradle, interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadFromMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadFromTemplateService.java, interlok-core/src/main/java/com/adaptris/util/KeyValuePairSet.java, interlok-core/src/test/java/com/adaptris/core/MultiProducerWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/HttpHelper.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/HttpRequestServiceTest.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/StandardHttpProducerTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/JettyAsyncWorkflowInterceptorTest.java, interlok-core/src/test/java/com/adaptris/core/marshaller/xstream/PrettyStaxDriverTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/PayloadFromTemplateTest.java
- Add a payload-from-template service instead.
- Modify payload-from-metadata javadocs to indicate that you're abusing it
=> Deprecate payload-from-metadata

interlok-core/src/main/java/com/adaptris/core/management/jetty/FromXmlConfig.java
If your installation directory contains a space, then you get a URISyntaxException when you attempt to start the jetty component
Use new URI().toAsciiString() so that we get an encoded string we can just append to "file:///"
No functional change if you don't have spaces in your install dir.
Working jetty if you do.
Install to a directory with spaces (why would you, spaces are bad).
=> INTERLOK-3201 Support spaces in path when creating jetty.xml URL

interlok-core/src/main/java/com/adaptris/core/common/MetadataOutputStreamWrapper.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamOutput.java, interlok-core/src/test/java/com/adaptris/core/common/ByteArrayMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/common/MetadataStreamOutputTest.java
Since AWS-KMS has a 4096 byte restriction on what you can sign; you're expected to generally use the DIGEST type (i.e. do a hash first of the payload you want to sign) which means that your usage chain is probably going to be 
```
<payload-hashing-service>
<hash-algorithm>SHA-256</hash-algorithm>
<byte-translator class="base64-byte-translator"/>
<metadata-key>payload-hash</metadata-key>
</payload-hashing-service>
... the KMS stuffs.
```
When signing whatever it is you're going to sign, you get a ByteBuffer back from the request, which we would want to store it as metadata; since it would be rather obtuse to "overwrite the payload with a cryptographic signature". The current message-wrapper implementations for metadata don't support auto-translating bytes into base64 or whatever; and since …
=> INTERLOK-3211 Add a metadata-stream-output that includes a translator

interlok-core/src/main/java/com/adaptris/core/management/ManagementComponentFactory.java, interlok-core/src/main/java/com/adaptris/core/management/ManagementComponentInfo.java, interlok-core/src/main/java/com/adaptris/core/management/UnifiedBootstrap.java, interlok-core/src/main/java/com/adaptris/core/runtime/AdapterRegistry.java, interlok-core/src/main/java/com/adaptris/core/runtime/AdapterRegistryMBean.java, interlok-core/src/test/java/com/adaptris/core/management/AlwaysFailDummyManagementComponent.java, interlok-core/src/test/java/com/adaptris/core/management/ManagementComponentFactoryTest.java
We can configure management components in the bootstrap.properties, but then they are forgotten.  Almost like mini programs that run in the background.  What if we later want to know what management components are running?  Or even if they all started up correctly?
Firstly I have had to modify the ManagementComponentFactory such that it returns a list of information on running management components; a new class ManagementComponentInfo.
I've also taken the time to make the ManagementComponentFactory less rubbish, by  removing all the reflection.
The AdapterRegistry exposes a bunch of JMX endpoints, it also now exposes a list of management components, including their current state; init, start, stop and closed.
You'll need to start the adapter with at least one management component, then …
=> INTERLOK-3124 Added Management Components to JMX

interlok-core/src/main/java/com/adaptris/core/common/MetadataInputStreamWrapper.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataOutputStreamWrapper.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamInputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamOutputParameter.java, interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamParameter.java, interlok-core/src/test/java/com/adaptris/core/common/MetadataStreamDataOutputParameterTest.java
The handling by the UI of generics and how they build up the templates isn't great; there are some classes that implement multiple generic interfaces which breaks the UI and you have click a "refresh" button to make them come up.
I'm using the MessageWrapper interface for the new KMS services so am affected by this a fair amount.
Changed the hierarchy of MetadataOutputStreamWrapper / MetadataInputStreamWrapper so that
they don't extend the corresponding parameter versions.
Since MetadataOutputStreamWrapper no longer extends MetadataOutputStreamParameter; it can't be used as a DataOutputParameter
Since MetadataInputStreamWrapper no longer extends MetadataInputStreamParameter it cannot be used as a DataInputParameter
Both those *may break configuration*; however, given the name, this is …
=> INTERLOK-3211 Remove double generics

interlok-boot/src/main/java/com/adaptris/interlok/boot/InterlokLauncher.java, interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java, interlok-core/src/main/java/com/adaptris/core/management/NoAdapterBootstrap.java, interlok-core/src/main/java/com/adaptris/core/management/UnifiedBootstrap.java
This set of changes allow for the UI to be started without starting a local adapter. This can be useful in situations where a local adapter is not necessary, and the UI is only to connect to remote instances.
There are actually two sets of changes here, depending on which is deemed the more suitable:
1. A new bootstrap class that sets everything up but doesn't start an adapter
2. A command line option for the existing bootstrap that indicates the user wants Jetty only
What we need is a poll for which solution is the preferred one.
The end result, either way, is the same: the UI is started without a local adapter.
To test, fire it all up with something similar to either of the following:
java … com.adaptris.core.management.NoAdapterBootstrap
or
java … …
=> INTERLOK-2981 Add --jettyonly as a mode.

interlok-core/src/main/java/com/adaptris/core/services/metadata/MetadataValueEscapeDoubleQuote.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/MetadataValueEscapeSingleQuote.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/MetadataValueEscapeDoubleQuoteTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/MetadataValueEscapeSingleQuoteTest.java
Why am I doing this
New services for escaping the single and double quote characters in metadata values were requested.
What did I change
I created two new services in the core-services-metadata which escape the single and double quote characters adding a backslash before them.
Complimenting tests were also added for these two new services.
What's the end result for the user
The user may now add a service for escaping their metadata's values of single or double quote characters.
How can I test this if I'm reviewing this.
There are two ways to test. The first would be to run the added Junit tests and the second to build the core with the new services and drop the jars into a working instance of an Interlok adapter and add the service and use them.
=> INTERLOK-3214 New Metadata service Escape Single and Escape Double quotes

interlok-core/src/main/java/com/adaptris/core/cache/Cache.java, interlok-core/src/main/java/com/adaptris/core/cache/CacheEventLogger.java, interlok-core/src/main/java/com/adaptris/core/cache/ExpiringMapCache.java, interlok-core/src/main/java/com/adaptris/core/cache/ExpiringMapCacheListener.java, interlok-core/src/main/java/com/adaptris/core/cache/NullCacheImplementation.java, interlok-core/src/main/java/com/adaptris/core/services/cache/AddValueToCache.java, interlok-core/src/main/java/com/adaptris/core/services/cache/GetValueFromCache.java, interlok-core/src/main/java/com/adaptris/core/services/cache/RemoveKeyFromCache.java, interlok-core/src/main/java/com/adaptris/util/TimeInterval.java, interlok-core/src/main/java/com/adaptris/util/text/DateFormatUtil.java, interlok-core/src/test/java/com/adaptris/core/cache/CacheDefaultMethodsTest.java, interlok-core/src/test/java/com/adaptris/core/cache/CacheEventLoggerTest.java, interlok-core/src/test/java/com/adaptris/core/cache/ExpiringMapCacheTest.java, interlok-core/src/test/java/com/adaptris/core/cache/MyCacheEventListener.java, interlok-core/src/test/java/com/adaptris/core/cache/NullCacheImplementationTest.java, interlok-core/src/test/java/com/adaptris/core/services/cache/AddValueToCacheTest.java
If you are using OAUTH; then often you get `expires_in` which tells you when the token expires. This could differ from provider to provider; but you want to store all the tokens in the same cache. At the moment you need to set the cache to expire for the "shortest" provider; rather than having a per-item expiry, with the cache lifetime set to something longer.
Note that JSR107 cache implementions don't appear to allow for per-item expiry; so this probably doesn't work for anything other than the expiring-map-cache implementation that's bundled with interlok core.
Added new methods to the `Cache` interface; the default is to throw UnsupportedOperationExceptions which means no changes required to the things in interlok-cache 
Retrofit expiry into add-single-value-to-cache so that this …
=> INTERLOK-3158 per item cache expiry

interlok-core/src/main/java/com/adaptris/core/cache/CacheExpiry.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/AccessToken.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/AccessTokenBuilder.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/AccessTokenWriter.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/GetAndCacheOauthToken.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/GetOauthToken.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/MetadataAccessTokenWriter.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/OauthTokenGetter.java, interlok-core/src/main/java/com/adaptris/core/services/cache/AddValueToCache.java, interlok-core/src/test/java/com/adaptris/core/cache/CacheExpiryTest.java, interlok-core/src/test/java/com/adaptris/core/http/oauth/GetAndCacheOauthTokenTest.java, interlok-core/src/test/java/com/adaptris/core/http/oauth/GetOauthTokenTest.java, interlok-core/src/test/java/com/adaptris/core/http/oauth/MetadataTokenWriterTest.java
In almost all cases people want to get an OAUTH Access Token and re-use it repeatedly which means that they invariable have something like this as a shared-service (or any variation thereof).
```
<if>
<exists-in-cache/>
<then>
<get-single-value-from-cache/>
</then>
<otherwise>
<get-oauth-token/>
<add-single-value-to-cache/>
</otherwise>
</if>
```
Since this is a often used pattern (and in fact probably only use-case) then we should shorten the chain so it's not so unwieldy.
* Refactor the existing add-single-value-to-cache so that the cache-expiry logic is exposed via a helper method in c.a.c.c
* Refactor get-oauth-token so that we now encapsulate what we do with the tokean via a `access-token-writer` interface (the only impl is `oauth-access-token-to-metadata`).
* Add a …
=> INTERLOK-3225 auto cache oauth token

docs/adr/0007-jetty-failsafe.md
We need to be able start jetty w/o having it explicit configured. This is so we don't have artefacts that people don't change cluttering their git repos.
The ADR for this PR is here : 
https://github.com/adaptris/interlok/blob/INTERLOK-3219-jetty-without-explicit-configuration/docs/adr/0007-jetty-failsafe.md
Once merged it, the ADR will be here and overwrite the template one that you can see since it isn'ty merged  : 
https://github.com/adaptris/interlok/blob/develop/docs/adr/0007-jetty-failsafe.md
=> INTERLOK-3219 / ADR-0007 Jetty without explicit configuration

interlok-core/src/main/java/com/adaptris/core/RandomIntervalPoller.java, interlok-core/src/test/java/com/adaptris/core/RandomIntervalPollerTest.java
Why am I doing this
Clearer more human readable logging
What did I change
Improved logging readability by dividing hours, minutes, seconds and milliseconds into more manageable quantities.
What's the end result for the user
The Random Interval Poller now logs more human readable time based on user input
How can I test this if I'm reviewing this.
Run the tests, alternatively build and drop the Jar into an instance of Interlok and watch the logger (stop watch advisable).
=> INTERLOK-2895: Random Interval Poller TimeStamp

gradle/owasp-exclude.xml
Depedency check is currently reporting a false positive for `javax.websocket` jars.
```
javax.websocket-api-1.0.jar (pkg:maven/javax.websocket/javax.websocket-api@1.0, cpe:2.3:a:java-websocket_project:java-websocket:1.0:*:*:*:*:*:*:*) : CVE-2020-11050
javax.websocket-client-api-1.0.jar (pkg:maven/javax.websocket/javax.websocket-client-api@1.0, cpe:2.3:a:java-websocket_project:java-websocket:1.0:*:*:*:*:*:*:*) : CVE-2020-11050
```
Added suppression generated by dependency check to owasp exclude.
Report no longer reports the above as violations.
Update a project using the parent with the following config:
```
dependencyCheck  {
suppressionFiles= [ "https://raw.githubusercontent.com/adaptris/interlok/feature/INTERLOK-3284_owasp_javax_websocket/gradle/owasp-exclude.xml" ]
}
```
Run dependency …
=> INTERLOK-3284 add javax.websocket to owasp suppression

interlok-core/src/main/java/com/adaptris/core/HeartbeatEvent.java, interlok-core/src/main/java/com/adaptris/core/HeartbeatTimerTask.java, interlok-core/src/main/java/com/adaptris/core/LoggableEvent.java, interlok-core/src/test/java/com/adaptris/core/HeartbeatEventTest.java, interlok-core/src/test/java/com/adaptris/core/HeartbeatTimerTaskTest.java
We will need other implementations of the heartbeat event that can log their own messages.  Specifically a LicenseExpiryWarningEvent.
The timer task used to have a static message it would print for the heartbeat event, but now it will delegate to the heartbeat event to log as it sees fit, including log level.  To do this I have added another interface LoggableEvent that defines a single method logEvent(logger).
This change has no effect on the current behaviour.  The current HeartbeatEvents logEvent method has been added to reflect previous behaviour.
End users will eventually be able to configure different heartbeat event implementations who will be responsible for the log level and message they want to spit out.
Nothing has changed here if you still use the default HeartbeatEvent.
=> INTERLOK-3283

interlok-common/src/main/resources/com/adaptris/core/management/webserver/jetty-failsafe.xml, interlok-core/src/main/resources/META-INF/templates/template-jetty.xml, interlok-core/src/test/resources/jetty/jetty.xml
The default jetty-failsafe (and jetty.xml files that we distribute) contain a deprecated setting which causes a warning on startup.
```
[o.e.j.s.AbstractConnector] Ignoring deprecated socket close linger time
```
Remove the references to soLingerTime from the template jetty and jetty-failsafe
The warning should no longer be logged.
* Make sure you end up using the failsafe-jetty.xml; i.e. by `managementComponents=jmx:jetty` but no `webServerConfigUrl`
* Start it up
* Eyeball the logging (easiest if you are using log4j colourization); should be no warnings from jetty.
* Connect using the UI
* Create a new project
* Save it, opting to include all the "additional files"
* the jetty.xml that is saved should not have any soLingerTime
=> INTERLOK-3315 Remove soLingerTime

interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java, interlok-core/src/main/java/com/adaptris/core/management/config/ClasspathDupConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationCheckReport.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationCheckRunner.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationCheckersEnum.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationException.java, interlok-core/src/main/java/com/adaptris/core/management/config/DeserializationConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedConnectionConfigurationChecker.java, interlok-core/src/test/java/com/adaptris/core/management/config/ClasspathDupConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/ConfigurationCheckRunnerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeserializationConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/SharedConnectionConfigurationCheckerTest.java
The initial request was to have a new configuration test when starting an instance with --configtest to make sure shared connections were all referenced and being used in your channels and to make sure that any channels shared connections referenced a shared connection component.
We were already running 2 tests; classpath Dedup and an un-marshalling test.  I have abstracted these tests out into a new Interface ConfigurationChecker and impls.
I added a third implementation which will test the shared connections.
Currently these tests are a static list in a new enum; ConfigurationCheckersEnum.  So if you wanted to add a new configuration test, then you'd create a new implementation and add yours to the enum.
Each test returns a report object including any exception.
In the CmdBootstrap …
=> Interlok 2594 config test

docs/adr/0005-remove-produce-destination.md
It's a big change, so we need to think about the consequences.
https://github.com/adaptris/interlok/blob/adr/ADR-0005/docs/adr/0005-remove-produce-destination.md
(or after merge : https://github.com/adaptris/interlok/blob/develop/docs/adr/0005-remove-produce-destination.md)
=> ADR-0005 - Deprecate and remove Destination

interlok-core/src/main/java/com/adaptris/core/RestartProduceExceptionHandler.java
Restarting workflows on produce failures causes way more problems than it solves.  It shoujldn't be used.  So let's remove it.
Simply deprecated this restart produce exception handler.  The channel-restart-produce-exception-handler can still be used and does work (well once a bug is fixed in it, in this sprint).
I've said 3.11.0 as removal... do we want to stick with that or go higher?
EDIT:  Now set to 3.12
We're telling people not to use this.
Deprecation warnings should be thrown in the UI if you've configured this component.
=> INTERLOK-3277

interlok-common/src/main/java/com/adaptris/core/management/webserver/JettyServerManager.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/EmbeddedConnection.java
In some situations down to timing, you can have multiple RootContexts being created, which means that some things are added to the wrong context and never become available.
Make sure that addServlet is synchronized so that we don't have the chance to create multiple Root contexts.
Made the wait time in EmbeddedJettyConnection a bit more random...
Added `interlok.jetty.debug` in addition to `adp.jetty.debug` cos naming is important.
This is fine, since it's only executed in consumer#start
A marginally slower startup.
Most easily seen with
* workflow-rest-services (health-check)
* adapter with a single jetty workflow that takes no time to start.
* No UI.
Depending on the order in which you run, 3.10-SNAPSHOT / 3.10.1-RELEASE will show you logging about add multiple Root webapps : 
``` …
```
=> INTERLOK-3337 addServlet is now synchronized

interlok-core/src/main/java/com/adaptris/core/Channel.java, interlok-core/src/test/java/com/adaptris/core/ChannelTest.java
Why am I doing this
When the channel restarts after it's produce exception it still doesn't think it's back up and running, stopping any messages from being processed.
What did I change
Set the availability to true when the Channel is started.
What's the end result for the user
The channel fully restarts upon the channel produce exception handler.
How can I test this if I'm reviewing this.
Follow the instructions at Interlok-3230 to recreate, with the current change the channel will restart properly.
=> INTERLOK-3230 Channel Restart Produce Exception Handler

interlok-core/src/main/java/com/adaptris/core/services/cache/ClearCacheService.java, interlok-core/src/test/java/com/adaptris/core/services/cache/ClearCacheServiceTest.java
Add a simple service that clears the cache upon demand.
Added a ClearCacheService that invokes cache.clear() optionally ignoring the "UnsupportedOperationException" that's possible from the default cache.clear() method.
The ability to clear the contents of the cache outside of the normal expiry window.
Note that ehcache / jsr107 caching doesn't appear to support clear() (since it's not part of the JSR), so this really only works with the default expiring-map-cache implementation.
You'll need 3 workflows that can be triggered on demand.
- First one adds something to the cache.
- Second one retrieves that something from the cache (or fails)
- Third one clears the cache.
Execute 1/2/3/2 the last invocation of the 2nd workflow should fail.
=> INTERLOK-3340 Add a ClearCacheService

interlok-core/src/main/java/com/adaptris/core/AdapterXStreamMarshallerFactory.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/AddMetadataService.java, interlok-core/src/test/java/com/adaptris/core/BaseCase.java
To preserve "insertion order"; Set needs to be LinkedHashSet since XStream doesn't use the getters/setters and just uses its default implementation  when confronted with just a Set<> to unmarshal. Since we default to HashSet, we can't be sure that what's in the XML is what happens when we round trip since ordering minght change.
- Force the default implementation for Set to be LinkedHashSet when creating the XStream instance
- Change default set to be LinkedHashSet in AddMetadataService but not the method signature, so it's still Set<> for the getters and setters (this should have no real effect because of the first change).
- Modify roundtripEquality to be less strict when asserting equality
Done it this fashion (making roundtripEquality less strict) because there will be lots of …
=> INTERLOK-3342 Change default set to be LinkedHashSet

interlok-core/src/main/java/com/adaptris/core/management/ManagementComponentInfo.java
The bean required serialization so we could use it on a ui feature : 
INTERLOK-3251 - 'UI Dashboard - Add Adapter Management Info to the Information modal'
Added Serializable to the ManagementComponentInfo class, and made member 'instance' transient, as there's no point (i think) of this being part of the serialized object.
people can use the AdapterRegistryMBean.getManagementComponentInfo method (either jconsole or ui)
I tested using the UI dashboard information modal, from the branch:
interlok-ui (feature/INTERLOK-3251_Dashboard_Management_Information)
screenshot:
=> Added Serialization to the ManagementComponentInfo bean

interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/core/management/Constants.java, interlok-core/src/main/java/com/adaptris/core/management/config/AdapterConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ClasspathDupConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationCheckersEnum.java, interlok-core/src/main/java/com/adaptris/core/management/config/DeserializationConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/JavaxValidationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/XStreamConfigManager.java, interlok-core/src/main/java/com/adaptris/core/runtime/AdapterBuilder.java, interlok-core/src/test/java/com/adaptris/core/management/BootstrapPropertiesTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/ConfigurationCheckRunnerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeserializationConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/JavaxValidationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/MockBootProperties.java, interlok-core/src/test/java/com/adaptris/core/management/config/SharedConnectionConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/runtime/AdapterRegistryTest.java
At the moment `java -jar lib/interlok-boot.jar -configcheck` doesn't actually validate that the configuration is correct; and it should.
- Add a JavaxValidationChecker that uses Validation.buildDefaultValidatorFactory()
- Add a shared hierarchy for DeserializationCheck + JavaxValidationCheck so that we have common behaviour to get to the Adapter object.
- The config checkers no longer delegate to the AdapterRegistry but instead manage how to get to the "configuration" themselves. It would have been better to delegate it to AdapterBuilder but that's a weird rats nest.
- Changed the tests so that we don't mock BootstrapProperties since there is odd behaviour from mockito around returning null after multiple mock invocations; I suspect that it's because of the class member mocking but life …
=> INTERLOK-3286 javax validation config checker

interlok-core/src/main/java/com/adaptris/core/http/client/net/BranchingHttpRequestService.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/BranchingHttpRequestServiceTest.java
When branching on return codes from an Http Request, one HAS to set a default service ID, even though the modal does not show it as a required field.
If you don't set it; then you get a runtime exception (since it defaults to null).
```
Caused by: java.lang.IllegalArgumentException:  may not be null
at com.adaptris.interlok.util.Args.notNull(Args.java:32) ~[interlok-common.jar:3.10.2B2-RELEASE]
at com.adaptris.core.AdaptrisMessageImp.setNextServiceId(AdaptrisMessageImp.java:389) ~[interlok-core.jar:3.10.2B2-RELEASE]
at com.adaptris.core.http.apache.BranchingHttpRequestService.doService(BranchingHttpRequestService.java:111) ~[interlok-apache-http.jar:3.10.2B2-RELEASE]
at com.adaptris.core.BranchingServiceCollection.applyServices(BranchingServiceCollection.java:92) …
```
=> INTERLOK-3393 DefaultServiceId needs to be "" rather than null.

interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageListener.java, interlok-core/src/main/java/com/adaptris/core/CoreConstants.java, interlok-core/src/main/java/com/adaptris/core/FailedMessageRetrierImp.java, interlok-core/src/main/java/com/adaptris/core/ListenerCallbackHelper.java, interlok-core/src/main/java/com/adaptris/core/MultiProducerWorkflow.java, interlok-core/src/main/java/com/adaptris/core/NoRetries.java, interlok-core/src/main/java/com/adaptris/core/NullProcessingExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/PoolingWorkflow.java, interlok-core/src/main/java/com/adaptris/core/RetryMessageErrorHandlerImp.java, interlok-core/src/main/java/com/adaptris/core/StandardProcessingExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/StandardWorkflow.java, interlok-core/src/main/java/com/adaptris/core/StandardWorkflowImpl.java, interlok-core/src/main/java/com/adaptris/core/WorkflowImp.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsTransactedWorkflow.java, interlok-core/src/main/java/com/adaptris/core/jms/OnMessageHandler.java, interlok-core/src/main/java/com/adaptris/core/lms/LargeMessageWorkflow.java, interlok-core/src/test/java/com/adaptris/core/StandardWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsProducerCase.java, interlok-core/src/test/java/com/adaptris/core/jms/MockConsumer.java, interlok-core/src/test/java/com/adaptris/core/jms/MockProducer.java, interlok-core/src/test/java/com/adaptris/core/jms/OnMessageHandlerTest.java, interlok-core/src/test/java/com/adaptris/core/stubs/MockMessageListener.java
This has been a planned 2nd stage in handling success and failure of each processed message; where each consumer can specify the specific callbacks for each.
The first already complete stage allowed us to specify the success callback.
Why now?
Shortly we will be handling async messaging as per the JMS 2.0 spec and vendor specific API's.  This means we cannot use our current consume, process, commit/rollback then consume again model.  Instead the callbacks are futures allowing us to continue to consume messages and at some point later execute success/failure code for each message.
This is very necessary step to break us away from the model described above.
This one was quite tricky due to the number of edge cases that needed to be satisfied, therefore I have taken a few liberties rather …
=> Interlok 3373

interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java, interlok-core/src/main/java/com/adaptris/core/management/NoAdapterBootstrap.java, interlok-core/src/main/java/com/adaptris/core/management/ShutdownHandler.java, interlok-core/src/main/java/com/adaptris/core/management/SimpleBootstrap.java
If you set startQuietly=false in your bootstrap properties, then there's a high chance that the JVM won't exit, although multiple errors are logged.
You might expect startQuietly=false to kill the JVM, because you're deploying w/o the UI into production... (you could use alive/readiness instead which would probably do the same thing).
- Change the shutdown handler so that we don't wait for the mainThread since either a) it's already dead (normal), or b) it's about to call system.exit()
- Change BootstrapProperties so that we don't throw exceptions in the constructor since we don't need to.
- SimpleBootstrap now checks if we're starting quietly, and does sysexit if we aren't.
Probably no change for the user, since the default is `startQuietly=true`
Configure something like
```
<adapter> …
```
=> INTERLOK-3404  startQuietly=false now does system.exit()

interlok-core/src/main/java/com/adaptris/core/management/config/AdapterConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ClasspathDupConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationCheckRunner.java, interlok-core/src/main/java/com/adaptris/core/management/config/ConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedComponentConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedConnectionConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedServiceConfigurationChecker.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.core.management.config.ConfigurationChecker, interlok-core/src/test/java/com/adaptris/core/management/config/ClasspathDupConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeserializationConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/JavaxValidationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/SharedConnectionConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/SharedServiceConfigurationCheckerTest.java
Since we are already checking shared connections we should also have a configuration check that checks shared-services via XML in the same way
- Add a new config checker that make sure that all the SharedService lookupName are valid and exists in shared components services.
- Add a test class that validate the new config checker
- Extract the common code between the shared service and shared connection config checker into an abstract class.
- Remove the UnifiedBoostrap param from ConfigurationChecker#performConfigCheck as it isn't use anywhere.
An error is reported in the config check runner if the a SharedService has a lookupName  which doesn't reference a valid SharedComponents Service.
The tests should be successful.
Add a shared service in a workflow with an invalid lookupName:
``` …
```
=> Interlok 3398 Config check should also check references from SharedService exist in shared-components

interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyMessageConsumer.java, interlok-core/src/main/java/com/adaptris/core/services/exception/ClearExceptionService.java, interlok-core/src/main/java/com/adaptris/core/util/MessageHelper.java, interlok-core/src/test/java/com/adaptris/core/services/exception/ClearExceptionServiceTest.java, interlok-core/src/test/java/com/adaptris/core/util/MessageHelperTest.java
If you configure a jetty consumer, but the client is a bit shit and does `Content-Type: text/plain; charset=UTF-9`
Then you get this
```
2020-08-17T12:05:31,474 WARN  [qtp1550820587-33] [HttpChannel] /login
java.nio.charset.UnsupportedCharsetException: UTF-9
at java.nio.charset.Charset.forName(Charset.java:541) ~[?:?]
at com.adaptris.core.AdaptrisMessageImp.setContentEncoding(AdaptrisMessageImp.java:160) ~[interlok-core.jar:3.10.2-RELEASE]
```
Which means you can't fire normal error handling because well, UTF-9 doesn't exist as a valid charset, so we never get to the stage of entering the workflow. This may also have the side-effect of invalidating the servlet...
- If request.getCharacterEncoding() is invalid, then we don't try to set it, and add an exception to ObjectMetadata.
This …
=> INTERLOK-3405 jetty-consumer can now default encoding

interlok-common/src/main/java/com/adaptris/interlok/util/CloseableIterable.java, interlok-common/src/test/java/com/adaptris/interlok/util/CloseableIterableTest.java, interlok-core/src/main/java/com/adaptris/core/util/CloseableIterable.java, interlok-core/src/test/java/com/adaptris/core/util/CloseableIterableTest.java
`CloseableIterable` was moved out of com.adaptris.core.util (interlok-core) into com.adaptris.interlok.util (interlok-common) in 3.10.2; The core.util version was deprecated at the same time. 
The relationship is one way from interlok-core to interlok-common; since we can't really have a relationship from interlok-common to interlok-core as that would cause circular package dependencies. Traditionally, I would have made the core.util version the parent super-class to the interlok.util version and deprecated it, which would avoid the complication that we have now).
However, because of this if we have classes that mix and match the old and the new (either knowingly or indirectly).
`com.adaptris.core.util.CloseableIterable#ensureClosable(com.adaptris.interlok.util.CloseableIterable)` will …
=> Fix an edge case issue around ensuring Closeable

interlok-core/src/main/java/com/adaptris/core/services/splitter/AdvancedMessageSplitterService.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/BasicMessageSplitterService.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/MessageSplitterServiceImp.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/PoolingMessageSplitterService.java, interlok-core/src/main/java/com/adaptris/core/services/splitter/ServiceWorkerPool.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/BasicMessageSplitterServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/PoolingMessageSplitterServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/ServiceExceptionHandlerTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/ServiceWorkerPoolTest.java
If have a message that has many many messages when split (e.g. a LineCountSplitter on a 80k line file) then you end up with a list of 80k futures. This is undesirable from an object count of point of view vis-a-vis object creation, since this effectively doubles the number of object references (1 for the split message, and 1 for the future).
- Add a Consumer<Exception> callback to MessageSplitterServiceImp that concrete sub-classes know about
- Make the concrete subclasses use the callback on success or failure which is then tracked to make sure that we throw
an exception as required.
- Add a "wait-while-busy (default=false)" mode to pooling-message-splitter so that it proactively checks the size of the object pool before submitting; waits a while if num-active >= max-allowed.
- This has …
=> INTERLOK-2611 split many messages

interlok-core/src/main/java/com/adaptris/core/services/splitter/PoolingMessageSplitterService.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/PoolingMessageSplitterServiceTest.java, interlok-core/src/test/java/com/adaptris/core/util/LifecycleHelperTest.java
https://github.com/adaptris/interlok/pull/514 caused a drop in performance while wait-while-busy=true. For a simplistic test, generating 52k split messages, we ended up taking 50times longer than wait-while-busy=false.  Which is expected if we just do the maths.
- There are 52k messages coming out of the split.
- Each split message "takes no time to process"; since it's just a raw write to disk, so we can expect the entire thread pool to be emptied at the same time (near as dammit).
- This means that the total wait time is possibly (52k / 10 (the size of the pool)) * 100 -> which is 520k ms or ~10 minutes.
- The performance measuring shows that the time to process is 320k ms, so we're somewhat faster, however the bulk of this time is spent in Thread.sleep() for no reason.
Needed to fix …
=> INTERLOK-3425 pooling splitter wait while busy

interlok-core/src/main/java/com/adaptris/core/jms/JmsAsyncProducer.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsAsyncProducerEventHandler.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsAsyncProducerTest.java
After recently adding onAdaptrisMessage(message, success, failure) we have needed to update the async producer to take advantage of these callbacks when a future event of success or failure comes in.
The JmsAsyncProducer now uses a common method to that of SolaceJcsmpProducer in that it has a JMS 2.0 callback event handler (CompletionListener) registered.  The producer will register the JMS message with the adaptris message callbacks in the event handler.  Later when a success/failure event is caught we recall the adaptris message with the callbacks in it and execute them.
The async producer is now fully functional according to the JMS 2.0 spec.  In testing it's just as fast producing to WMQ (which supports jms 2.0 from version 8.0) as the solace native stuff.
You'll need a JMS 2.0 …
=> Async producer now handles success and failure callbacks.

interlok-common/src/main/java/com/adaptris/interlok/resolver/ExternalResolver.java, interlok-core/src/main/java/com/adaptris/core/management/vcs/RuntimeVersionControlLoader.java
You can get a 
```
com.adaptris.core.ServiceException: java.util.ConcurrentModificationException
at com.adaptris.core.transform.json.JsonTransformService.doService(JsonTransformService.java:677) ~[interlok-json.jar:3.11-SNAPSHOT]
at com.adaptris.core.ServiceList.applyServices(ServiceList.java:96) ~[interlok-core.jar:3.11-SNAPSHOT]
at com.adaptris.core.ServiceCollectionImp.doService(ServiceCollectionImp.java:204) ~[interlok-core.jar:3.11-SNAPSHOT]
at com.adaptris.core.services.splitter.ServiceWorkerPool$Worker.doService(ServiceWorkerPool.java:169) ~[interlok-core.jar:3.11-SNAPSHOT]
at com.adaptris.core.services.splitter.PoolingSplitJoinService$MyServiceExecutor.call(PoolingSplitJoinService.java:183) [interlok-core.jar:3.11-SNAPSHOT]
at …
```
=> INTERLOK-3432 Only do ServiceLoader once in a singleton

interlok-core/src/main/java/com/adaptris/core/config/ConfigPreProcessorLoader.java, interlok-core/src/main/java/com/adaptris/core/management/config/AdapterConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedComponentConfigurationChecker.java
If your configuration is 
```
<adapter xmlns:xi="http://www.w3.org/2001/XInclude">
<shared-components>
<xi:include href="connections.xml"/>
</shared-components>
</channel-list>
<channel>
<consume-connection class="shared-connection">
<lookup-name>something defined in connections.xml</lookup-name>
</consume-connection>
</channel>
</channel-list>
</adapter>
```
Because you love xincludes then java -jar lib/interlok-boot.jar does not work since the shared confugiration checker doesn't believe in pre-processors.
Add a helper method into ConfigPreProcessorLoader that does the right thing as a helper method which basically looks like this : 
```
static String loadInterlokConfig(BootstrapProperties config) throws Exception {
String result = "";
try (InputStream in = …
```
=> INTERLOK-3437 Shared component checker now uses pre-processors

interlok-core/src/main/java/com/adaptris/core/ResolveFromPayloadUsingXPath.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.interlok.resolver.Resolver, interlok-core/src/test/java/com/adaptris/core/resolver/ResolveFromPayloadUsingXPathTest.java
Using the same package as the resolver in interlok-core causes issues with the JavaDoc.
Move the JSON resolver package.
The JavaDoc should no longer be broken.
https://nexus.adaptris.net/nexus/content/sites/javadocs/com/adaptris/interlok-json/3.11.0-RELEASE/com/adaptris/core/resolver/package-summary.html should not include broken JavaDoc links.
=> INTERLOK-3434 Change package of resovler class

interlok-core/src/main/java/com/adaptris/core/jms/JmsMessageConsumerFactory.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsMessageConsumerFactoryTest.java, interlok-core/src/test/java/com/adaptris/core/jms/activemq/EmbeddedArtemis.java
Creating a durable subscriber was broken.  However, we were probably getting away with it while testing against ActiveMq because it didn't check to make sure the subscription name was null/empty.  The artemis broker does however which threw an pointed out this error.
We're now using the  subscription name when creating a durable subscriber in the JmsMessageConsumerFactory.
I've also used a static embedded broker and set the connection reconnects in an attempt to fix timing issues in the JmsConsumerTest.
Fingers crossed the unit tests won't fail periodically.
Durable subscribers can now be created correctly.
=> Interlok 3455

interlok-core/src/main/java/com/adaptris/security/password/Password.java, interlok-core/src/main/java/com/adaptris/security/password/PbeCrypto.java, interlok-core/src/test/java/com/adaptris/core/jdbc/PasswordProtectedDatabaseConnectionTest.java, interlok-core/src/test/java/com/adaptris/core/security/EncryptionServiceCase.java, interlok-core/src/test/java/com/adaptris/interlok/junit/scaffolding/jms/JndiImplementationCase.java, interlok-core/src/test/java/com/adaptris/security/TestPassword.java, interlok-core/src/test/java/com/adaptris/security/password/PasswordTest.java
https://lgtm.com/rules/7870098/ rightly marks `PBEWithSHA1AndDESede` as weak crypto.
Since as a style `ALTPW` is unloved (the UI doesn't support, it's not effectively transferable across hosts); it is of little impact to deprecate it and mark it for removal
- Deprecate ALTPW: and supporting files; marking for removal in 4.0
- Remove from the list that's emitted as the help for Password#main()
- Remove use of ALTPW internally within the tests.
- Mark with lgtm exclusion on the line's using the weak crypto.
- The UI doesn't support it, so there's no change to the user.
- The tests still pass; since the only change is annotational / documentation.
=> INTERLOK-340 Deprecate PbeCrypto

interlok-core/src/main/java/com/adaptris/core/services/path/XPathService.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/XpathMetadataServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/path/XPathServiceTest.java
Why am I doing this
I discovered that when retrieving a single attribute node in the XPath Service the service would simply throw an exception rather than return the value
What did I change
I updated the Xpath service to resolve attribute nodes and updated the service's tests to reflect this.
What's the end result for the user
The user can now resolve single attribute nodes with the Xpath service
How can I test this if I'm reviewing this.
The tests have been updated and cover the changes.
You can also build the project, drop the jar into a working adapter and query an xpath attribute node to confirm
=> INTERLOK-3460 xpath service attribute node support

interlok-core/src/main/java/com/adaptris/core/CoreConstants.java, interlok-core/src/main/java/com/adaptris/core/ServiceListBase.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/DoWhile.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/ForEach.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/While.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/DoWhileTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/ForEachTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/WhileTest.java
A recent QandA message suggested that our conditional loops (while and do-while) continue looping after a stop-processing-service.
ServiceList's do actually test for the metadata set by the stop-processing-service, so you could argue that even though the conditional loops will continue spinning, no services will be applied.
But what if you use a service that has nested services and one of those nested services is a stop-processing-service.
This behaviour doesn't make sense for the for-loop, considering that loop uses a different payload for each iteration.  Also each payload has the services run in parallel threads making the behaviour of stopping exactly as soon as one of the threads runs a stop-processing thread difficult to predict.  
I think this PR can be argued either way. …
=> INTERLOK-3472 Stop processing Conditional loops

interlok-core/src/main/java/com/adaptris/core/MultiPayloadAdaptrisMessageImp.java, interlok-core/src/test/java/com/adaptris/core/MultiPayloadMessageFactoryTest.java
Discovered that the ternary operator was incorrect when testing the MS Azure/Graph mail consumer/producer.
Flipped the results of the ternary operator.
The resolve now works correctly.
I added to the resolve test case my originally non-working example, which now works as expected.
=> Correct dotAll usage for regex in resolve method

interlok-core/src/main/java/com/adaptris/core/jdbc/C3P0PooledDataSource.java, interlok-core/src/main/java/com/adaptris/core/jdbc/HikariPoolBuilder.java, interlok-core/src/main/java/com/adaptris/core/jdbc/PluggableJdbcPooledConnection.java, interlok-core/src/main/java/com/adaptris/core/jdbc/PooledDataSourceImpl.java
If you use the Hikari connection pool via pluggable-jdbc-connnection-pool; and the database is not available, then 
`java -jar lib/interlok-boot.jar -configcheck` doesn't work.
So, if you have this simple configuration, and you don't have a mariaDB instance on localhost running, then -configcheck will fail.
```xml
<adapter>
<unique-id>MyInterlokInstance</unique-id>
<shared-components>
<connections>
<pluggable-jdbc-pooled-connection>
<unique-id>jdbc-pooled-connection</unique-id>
<test-statement>SELECT DATABASE(), VERSION(), NOW(), USER();</test-statement>
<driver-imp>com.mysql.jdbc.Driver</driver-imp>
<always-validate-connection>true</always-validate-connection>
<username>root</username>
<password>root</password>
<connect-url>jdbc:mysql://localhost:3306/mysql?autoReconnect=true</connect-url …
```
=> INTERLOK-3463 Make the HikariPoolBuilder "lazier"

interlok-core/src/main/java/com/adaptris/core/management/config/DeprecatedConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/JavaxValidationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ValidationCheckerImpl.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/JavaxValidationCheckerTest.java
If you have a consumer (the only consumer in the only workflow in the only channel)
```xml
<consumer class="jetty-message-consumer">
<unique-id>csv-receive</unique-id>
<destination class="configured-consume-destination">
<destination>/api/csv</destination>
</destination>
<parameter-handler class="jetty-http-ignore-parameters"/>
<header-handler class="jetty-http-headers-as-metadata"/>
</consumer>
```
And you run `gradle check` in a parent gradle style project then you get 4 deprecation warnings; they all refer to the same element, but manifest themselves because `channelList` implements List and has a `Valid` annotation, ditto `workflowList`
```
Deprecated checks:
Warnings found;
Interlok Deprecation Warning: [channelList.channels[0].workflowList[0].consumer.destination] is deprecated. Use …
```
=> INTERLOK-3491 Use regexp to filter out duplicates

interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/RetryFromJetty.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/RetryStore.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryFromJettyTest.java
Since https://github.com/adaptris/interlok/pull/556 doesn't expose DELETE functionality; we should add it. Since @mcwarman  was complaining that he had to have additional workflows to support that.
- Add a DeleteListener that handles deletes from the store; it works like the retry listener
- Relies on getMetadata() to fail if the message-id is not found.
New endpoint is available that allows you to do : 
```
curl -XDELETE http://localhost:8080/api/failed/delete/[msgId]
```
Configuration as per https://github.com/adaptris/interlok/pull/556. It should now be possible to delete messages from the retry store.
=> INTERLOK-3501 Add delete functionality

interlok-core/src/main/java/com/adaptris/core/management/config/AdapterConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/CachingConfigLoader.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedComponentConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/SharedServiceConfigurationChecker.java, interlok-core/src/test/java/com/adaptris/core/management/config/CachingConfigLoaderTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/MockBootProperties.java
If you have a shared service defined via its class alias (rather than as an element), then it is ignored by the shared-service checker, which results in a false positive on the warning output when you run -configcheck.
Given this example :
```
<exception-handling-service-wrapper>
<unique-id>profile-exception-wrapper-in-query</unique-id>
<service class="service-list">
<unique-id>do-stuff-that-might-fail</unique-id>
....
...
....
</service>
<exception-handling-service class="shared-service">
<lookup-name>invalid-profile-error</lookup-name>
<unique-id>product-structure-validation-query</unique-id>
</exception-handling-service>
<exception-message-metadata-key>exceptionMessage</exception-message-metadata-key>
</exception-handling-service-wrapper>
```
The shared service `invalid-profile-error` …
=> INTERLOK-3508 Add support for multiple reference xpaths

interlok-core/src/main/java/com/adaptris/core/management/config/DeprecatedConfigFileReporter.java, interlok-core/src/main/java/com/adaptris/core/management/config/DeprecatedConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/util/LoggingHelper.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.core.management.config.ConfigurationReporter, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigFileReportTest.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigurationCheckerTest.java
To simplify things for the interlok-verify-report out of the parent build.gradle; we need to make the config checker integrate loosely with it.
Since the task works off the back off a file that is emitted via log4j configuration based on the warnings; we can make -configcheck write a file in the same format.
- Add a DeprecatedConfigFileReporter that operates based on system properties
- Modify DeprecationConfigChecker so that it includes the unique-id + classname if available.
- Add Tests.
```
java -Dinterlok.verify.deprecated.filename=./report.txt -jar lib/interlok-boot.jar -configcheck
```
Now emits a report.txt -> if the system property denoting the filename is not present, then no data is written to file.
Available system properties are : 
```
interlok.verify.deprecated.filename
// …
```
=> INTERLOK-3497 - Add a system property based file report

interlok-core/src/main/java/com/adaptris/core/management/config/DeprecatedConfigurationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/JavaxValidationChecker.java, interlok-core/src/main/java/com/adaptris/core/management/config/ValidationCheckerImpl.java
The changes from https://github.com/adaptris/interlok/pull/579 introduced a leaf node report into when emitting deprecation warnings.
This should also be in the javax validation checker
- When running the config checker with javax validation report on the leaf bean that caused the violation.
If you have a javax validation error; then it will also print out the friendly name (classname + uniqueid)
If you have a service badly configured
```
<http-request-service>
<unique-id>http-request-service-without-url</unique-id>
</http-request-service>
```
Then you now get the output : 
```
javax.validation checks:
Failed with exceptions:
Interlok Validation Error: [channelList.channels[0].workflowList.workflows[0].serviceCollection.services[0].url][HttpRequestService(http-request-service-without-url)] …
```
=> INTERLOK-3526 Report the leaf for javax validation config check

interlok-core/src/main/java/com/adaptris/core/management/config/WarningsToFile.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.core.management.config.ConfigurationReporter, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigFileReportTest.java
https://github.com/adaptris/interlok/pull/579 was limited in scope since it only checked the deprecation warnings.
However, since this is a configuration reporter; we can actually report on all warnings.
- Rename DeprecatedConfigChecker to be WarningsToFile
- Add support for the shared-component checkers.
The properties change to (which is OK, since it only breaks snapshot).
```
interlok.verify.warning.filename
// default is CODE_SMELL
interlok.verify.warning.category
// default is INFO
interlok.verify.warning.level
```
Take the configuration from https://github.com/adaptris/interlok/pull/579 and add in some shared components.
```
<shared-components>
<connections>
<null-connection>
<unique-id>unused-null-connection</unique-id>
</null-connection>
</connections>
<services>
<service-list> …
```
=> INTERLOK-3497 shared components in report

interlok-core/src/main/java/com/adaptris/core/common/MetadataStreamOutputParameter.java, interlok-core/src/test/java/com/adaptris/core/common/MetadataStreamDataOutputParameterTest.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/StandardHttpProducerTest.java
A report suggested in certain situations our StandardHttpProducer's request method can throw an NPE.  It requires a response code <= 200 and >= 400 where the error response stream is null.
Turns out this is caused by configuring a MetadataStreamOutputParameter as the response handler.
PayloadStreamOutputParameter checks for null streams in the IOUtils.copy(), the metadata version does this also but first creates a reader object with the input stream, this causes an NPE.
We now check for a null stream and only perform the copy if the stream is not null.  In either case the metadata item is still  created.
NPE will no longer be thrown by the MetadataStreamOutputParameter if the stream is null.
Check the new unit test in the StandardHttpProducerTest class, this shows how to configure the …
=> Interlok 3527

interlok-core/src/main/java/com/adaptris/core/transform/XmlTransformService.java, interlok-core/src/main/java/com/adaptris/util/XmlUtils.java, interlok-core/src/main/java/com/adaptris/util/text/xml/Validator.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XPath.java
At the moment whenever you call `new com.adaptris.util.xml.XPath()` there is a call to Class.forName() to figure out which XpathFactory that it really wants to use (this is because Saxon is no longer available via XPathFactory.newInstance()) so we have to figure out which one to use.
The naiive use of Class.forName() can end up blocking Threads, most of the time it doesn't but high thread count + lots of XPaths...
```
java.lang.Thread.State: BLOCKED (on object monitor)
at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
- waiting to lock <0x00000006c03be418> (a java.lang.Object)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native Method)
at …
```
=> INTERLOK-3528 xpath Class.forName()

interlok-core/src/main/java/com/adaptris/core/jms/JmsConsumer.java, interlok-core/src/main/java/com/adaptris/core/jms/PasConsumer.java, interlok-core/src/main/java/com/adaptris/core/jms/PtpConsumer.java, interlok-core/src/test/java/com/adaptris/core/jms/PasConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/jms/activemq/BasicActiveMqProducerTest.java
Even though durable is deprecated, this is still required as configuration otherwise everything is a non-durable subscriber
In order for the subscriber to be durable, you still need `durable=true`. This was a regression introduced into PasConsumer by the changes for 3.11.0.
Change durable() method to be 
```
boolean durable() {
return BooleanUtils.or(new boolean[] {
BooleanUtils.toBooleanDefaultIfNull(getDurable(), false),
!StringUtils.isBlank(getSubscriptionId())
});
}
```
Regression is fixed from 3.11.0
Confirm the bug  in 3.11.x
- Start your JMS Broker of choice.
- 3.11.1 -> Create a PasConsumer with a subscriptionId but no "durable flag".
- Produce some messages to the topic and confirm they are consumed.
- Kill the consumer channel.
- Produce some more messages, and then restart the …
=> INTERLOK-3537 JMS durable subscriber is not durable with just subscription-id

interlok-core/src/main/java/com/adaptris/core/RestartProduceExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyRouteSpec.java, interlok-core/src/main/java/com/adaptris/core/http/oauth/GetOauthToken.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadFromMetadataService.java, interlok-core/src/main/java/com/adaptris/core/transform/XmlSchemaValidator.java, interlok-core/src/main/java/com/adaptris/core/util/CloseableIterable.java
Config components are marked as being removed in 3.12.0 but these changes are now being delayed until 4.0.0
updated the ConfigDeprecated/Removal annotations
any warnings generated from config checker / ui will be correct
just eyeball the changes and make sure nothing stupid was done
=> updated the ConfigDeprecated/Removal annotations; from 3.12 to 4

interlok-core/src/main/java/com/adaptris/core/PoolingWorkflow.java, interlok-core/src/main/java/com/adaptris/core/ThreadContextWorkflow.java, interlok-core/src/main/java/com/adaptris/core/WorkflowWithObjectPool.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyNoBacklogInterceptor.java, interlok-core/src/test/java/com/adaptris/core/ThreadContextWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/WorkflowWithObjectPoolTest.java
From @gerco 
>When running a bunch of PoolingWorkflows with an embedded Jetty connection, I'm noticing various performance issues depending on configuration:
>
>If the jetty executor is set to some number threads and each pooling workflow is set to fewer threads, a situation can occur where one PoolingWorkflow is swamped with work and has dozens of Jetty threads waiting for an available thread in the PoolingWorkflow.
>
>If the Jetty executor is set to the some number of threads and each pooling workflow is set to the same number, we are running many more threads than we ideally would. This is causing issues with dynamic-shared-services caching since these caches can be very large and per-thread so we run out of memory.
>
>Is there a way to run workflows directly on the Jetty threads …
=> INTERLOK-3561 ThreadContextWorkflow

interlok-core/src/main/java/com/adaptris/core/jdbc/DatabaseConnection.java
There is an issue with the DatabaseConnection, the field testStatement was marked as Deprecated, but it was left as a required field. 
This means you can not blank this deprecated field. 
This issue is being tracked in 'INTERLOK-3580'.
removed the annotation that makes it required; changed the constructor so it doesn't auto populate test statement.
you should be able to use jdbc connections  and  have blank values in the test statement field
use the UI, create config, add connection, create a JdbcPooledConnection using some arbitrary defaults
Save the configuration.
if you re-edit and switch to export mode, you'll see the test statement field, try saving the component with and without a value.
this should work.
You should also get the warning "JdbcPooledConnection has a deprecated member …
=> INTERLOK-3580 removed the required annotation from the deprecated field

interlok-core/build.gradle
Use the latest derby version that integrates better with java11
Upgrade derby to 10.15.2.0
Nothing should change on how Interlok works
Tests should pass
=> INTERLOK-2963 #comment Upgrade Derby DB to 10.15.2.0

build.gradle
If you import the project into eclipse; it doesn't work and comes up with hundreds of errors along the lines of "package X is accessible from multiple modules 'un-named' && java something"
This is a side effect of the JPMS system, which has always existed but is now being enforced by Eclipse on Java11+ projects (or something).
If our java build is > 1.9 then we exclude jars that might be included by transitive dependences that don't play nice with JPMS.
- Eclipse should now work
- `./gradlew test` should still work, since the java runtime is "less strict that eclipse".
- Withouht this branch import the current develop branch into eclipse (you'll need to have made eclipse Java11 aware).
- It should have a bunch of errors and won't build.
- Switch to this branch, it should build.
Note that …
=> INTERLOK-3706 Add exclusion specific for java11+eclipse

interlok-core/src/test/java/com/adaptris/core/jms/JmsProducerTest.java
Should have merge develop into feature branch before merging back into develop.
A new test was introduced which used a `ConfiguredProduceDestination`, whereas now the `createProducer()` method just accepts a `String`
Update the test to removed the `ConfiguredProduceDestination`
The unit tests now compile.
A simple `gradle build`
=> INTERLOK-3567 - Update for new test

interlok-core/src/main/java/com/adaptris/core/services/ScriptingServiceImp.java, interlok-core/src/test/java/com/adaptris/core/services/EmbeddedScriptingServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/ScriptingServiceTest.java
Nashorn script engine is deprecated and will be removed in Java 17 so we need to warn users of ScriptingService and EmbeddedScriptingService and propose an alternative.
- When using a scripting service the code now check if the script language is a nashorn supported language("js", "javascript"...)  and log a warning if it is and GraalJS is not in the classpath.
- If the script language is "nashorn" we log a warning regardless if GraalJS is in the classpath or not.
- Added new tests
Graaljs supports the all the javascript names Nashorn supports ("js", "JS", "JavaScript", "javascript", "ECMAScript", "ecmascript") so we don't need to do any translation.
The adapter need to be started with a system property so GraalJS works the same way as Nashorn:
`polyglot.js.nashorn-compat=true`
In the …
=> INTERLOK-3439 Log a warning when a javascript name is used with a scripting service

build.gradle, interlok-core/build.gradle
Support for JSCH by org.jcraft has discontinued and the last update was compiled for 1.6
Java 11 can only read class files compiled for a minimum Java version of 1.8
We're now using com.github.mwiede:jsch:0.1.62, last updated this month.
We can now run Interlok components that require JSCH in a Java 11 runtime.
See the following test project.  It is currently configured in the gradle.build to exclude org.jcraft and include the new replacement.  If you build this project removing the exclude and new include the project will fail to start-up in a Java 11 runtime.
[vcs-git-testing.zip](https://github.com/adaptris/interlok/files/6101760/vcs-git-testing.zip)
=> INTERLOK-3740 JSCH Java 11

interlok-core/src/main/java/com/adaptris/core/util/DocumentBuilderFactoryBuilder.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/XpathMetadataServiceTest.java, interlok-core/src/test/java/com/adaptris/core/util/DocumentBuilderFactoryBuilderTest.java
XpathMetadataService is using DocumentBuilderFactoryBuilder.newInstanceIfNull, which relies on the underlying document factory for things like XXE mitigations. It should probably be using newRestrictedInstanceIfNull instead to explicitly disable things like doctype and entity handling.
On the same note, DocumentBuilderFactoryBuilder should be setting those same features to "off" when not configured rather than rely on the default underlying DocumentBuilderFactory configuration.
This change will not break config directly, but it will break currently-working functionality if someone was relying on those featured being defaulted on in some DocumentBuilderFactory implementations.
- newInstance() now just delegates to newRestrictedInstance()
- Modify enums so that the new "secure" defaults are …
=> INTERLOK-3573 XML services should use a restricted instance to mitigate against XXE

interlok-core/src/main/java/com/adaptris/core/util/DestinationHelper.java
Re-add the DestinationHelper to make it easier to remove all optional references to Destination.
Re-add DestinationHelper but remove method parameters for legacy and force it to be null instead.
No change for end user but should help devs with removing all references to Destination.
There are no tests as this is only to help devs remove references to Destination.
=> INTERLOK-3566 Re-add DestinationHelper

interlok-core/src/main/java/com/adaptris/core/util/DestinationHelper.java, interlok-core/src/test/java/com/adaptris/core/util/DestinationHelperTest.java
Re-add tests DestinationHelper
Re-add tests DestinationHelper and update JavaDoc, mark the methods as Deprecated.
There are now unit tests to run and the JavaDoc matches the methods.
Tests run as expected.
=> INTERLOK-3566 Re-add tests and update javadoc

interlok-core/src/main/java/com/adaptris/core/EventFactory.java, interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/core/management/ManagementComponentFactory.java, interlok-core/src/main/java/com/adaptris/core/management/properties/PropertyResolver.java, interlok-core/src/main/java/com/adaptris/core/management/vcs/RuntimeVersionControlLoader.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/types/DoubleColumnTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/types/FloatColumnTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/types/IntegerColumnTranslator.java, interlok-core/src/main/java/com/adaptris/security/certificate/X509Builder.java, interlok-core/src/main/java/com/adaptris/security/keystore/KeystoreFactory.java, interlok-core/src/main/java/com/adaptris/sftp/SftpClient.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XPath.java, interlok-core/src/test/java/com/adaptris/core/CoreExceptionTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/JdbcObjectMetadataParameterTest.java, interlok-core/src/test/java/com/adaptris/core/jms/JmsTransactedWorkflowTest.java, interlok-core/src/test/java/com/adaptris/core/jms/activemq/ActiveMqPasPollingConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/ForEachTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/types/BooleanColumnTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/types/DoubleColumnTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/types/FloatColumnTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/jdbc/types/IntegerColumnTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/jmx/MetadataValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/jmx/ObjectMetadataValueTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/ServiceExceptionHandlerTest.java, interlok-core/src/test/java/com/adaptris/core/services/splitter/ServiceWorkerPoolTest.java, interlok-core/src/test/java/com/adaptris/core/util/DestinationHelperTest.java, interlok-core/src/test/java/com/adaptris/security/AdaptrisSecurityExceptionTest.java
Java 9+ has deprecated a bunch of constructors; so this is a fairly non-contentious change to make sure we aren't burned later on.
- new Integer -> Integer.valueOf() (and so forth for the number types).
- Class.forName().newInstance() -> Class.forName().getDeclaredConstructor().newInstance() 
- Since getDeclaredConstructor() can throw NoSuchMethodException some tests had to have their exception handling widened.
- Add SuppressWarnings annotation where appropriate
Fewer deprecation warnings; no change for the user.
The tests still pass.
=> Remove java9 deprecated constructors

interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStore.java, interlok-core/src/main/java/com/adaptris/core/util/MessageHelper.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStoreTest.java, interlok-core/src/test/java/com/adaptris/core/util/MessageHelperTest.java
When using jetty-retry-store currently we don't write the stacktrace out anywhere, so you can't easily investigate the problem.
The stacktrace itself isn't "required to build up what needs to be retried", but could be useful information regardless.
- Add a method to `MessageHelper` to return an Optional wrapping the stack trace.
- If the stacktrace exists then it is written to the msgDir as _stacktrace.txt_ which means that it's available for further investigations as required.
If using the filesystem-retry-store then an extra file is present.
- No change for optional component implementations (such as AWS) at this time; the MessageHelper helper is propbably useful to make that work.
Use the configuration from https://github.com/adaptris/interlok/pull/556 ; however check that the files …
=> INTERLOK-3711 stacktrace as part of retry-store

interlok-core/src/main/java/com/adaptris/core/fs/FsConsumer.java, interlok-core/src/main/java/com/adaptris/core/fs/FsConsumerImpl.java, interlok-core/src/test/java/com/adaptris/core/fs/FsMessageConsumerTest.java
If the user tries to consume a large file using the standard FS consumer, an out-of-memory error will occur, which causes the adapter to hang.
Change the catch block so that it catches everything and rethrows wrapped in CoreException.
The error is now visible and the adapter doesn't require restarting.
The new unit test should demonstrate the issue - it doesn't actually fail, it just times-out, but zero messages are generted. There is also this simply FS consumer config [adapter.xml](https://github.com/adaptris/interlok/files/6375094/adapter.xml.txt) - as the ticket said, just try and consume a sufficiently large file (1GB-ish).
=> bug/interlok-3304 - Unckecked Exceptions in FsConsumer causes hang

interlok-core/src/main/java/com/adaptris/core/ftp/FtpConsumer.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpConsumerImpl.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpHelper.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpRecursiveConsumer.java, interlok-core/src/main/java/com/adaptris/filetransfer/FileTransferClient.java, interlok-core/src/main/java/com/adaptris/ftp/ApacheFtpClientImpl.java, interlok-core/src/main/java/com/adaptris/sftp/SftpClient.java, interlok-core/src/test/java/com/adaptris/core/ftp/FtpHelperTest.java, interlok-core/src/test/java/com/adaptris/core/ftp/FtpRecursiveConsumerTest.java, interlok-core/src/test/java/com/adaptris/sftp/test/TestSftp.java
The current FTP consumer will only consume files that are within the current working directory, without descending into any child directories. In certain situations it may be beneficial to scan sub directories too.
Add a new consumer that will recursively descend into any sub directories it find.
All files found in sub directories get consumed.
The unit tests mock a fake FTP server (which is how i discovered not all FTP servers are created equal or implement all commands). I also started an FTP server locally to confirm [adapter.xml](https://github.com/adaptris/interlok/files/6351491/adapter.txt).
=> feature/interlok-3588 - FtpConsumer - Add the posibility to consume files from subfolders

interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/ConfiguredXpathQuery.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/MetadataXpathQuery.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/MetadataXpathQueryImpl.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/MultiItemConfiguredXpathQuery.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/MultiItemMetadataXpathQuery.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/XpathMetadataQuery.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/xpath/XpathQueryImpl.java, interlok-core/src/main/java/com/adaptris/core/util/XmlHelper.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/xpath/ConfiguredXpathQueryTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/xpath/MetadataXpathQueryTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/xpath/MultiItemConfiguredXpathQueryTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/xpath/MultiItemMetadataXpathQueryTest.java, interlok-core/src/test/java/com/adaptris/core/util/XmlHelperTest.java
Dave would like have the xpath output of a nodeset NOT be rendered as ```for-each:node()/text()``` but to actually give a string representation of all the node matches.
So instead of:
2020-01 02  thing            12   whatever
2022-01 02  differentThing   6    whatever
2019-01 02  blah             9    whatever
He gets:
```xml
<fiscal_years>
<end_date>2022-12-31</end_date>
<fiscal_year>2022</fiscal_year>
<id>34F253E1-E65D-49B4-906C-D3642596D5D9</id>
<number_of_periods>12</number_of_periods>
<start_date>2022-01-01</start_date>
</fiscal_years>
<fiscal_years>
<end_date>2021-12-31</end_date>
<fiscal_year>2021</fiscal_year>
<id>8197BA42-CD21-4A53-A69C-E43F3271959E</id>
<number_of_periods>12</number_of_periods>
<start_date>2021-01-01</start_date>
</fiscal_years>
<fiscal_years> …
```
=> feature/INTERLOK-3757 - MultiItemXpathQuery that renders a node-list as a String of XML

interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionAnd.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionExpression.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionFunction.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionImpl.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionNot.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionOr.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ConditionPayload.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/Equals.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/IsEmpty.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/IsIn.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/IsNull.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/Matches.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/NotEmpty.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/NotEquals.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/NotIn.java, interlok-core/src/main/java/com/adaptris/core/services/conditional/operator/NotNull.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/conditions/ConditionMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/EqualsTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/IsEmptyTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/IsInTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/IsNullTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/MatchesTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/NotEmptyTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/NotEqualsTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/NotInTest.java, interlok-core/src/test/java/com/adaptris/core/services/conditional/operator/NotNullTest.java
Our logging for conditional services is either too verbose in places or just doesn't show anything useful, therefore we will review the logging for the conditions and fix up where appropriate.
We have a new logging method "logCondition" in the condition abstract class, all children conditions will call this method when they evaluate.  Additionally we have a new flag for this additionalLogging.  The flag defaults to false in case your data is sensitive and shouldn't be printed to logs.
The Operators now have a toString method that represents what they're testing; for example the Equals operator will return "equals myValue".
Any Condition that requires an Operator will call it's Operators toString method when building up the logging string; this means our conditions will log the condition …
=> INTERLOK-3326 Conditional Logging

interlok-core/src/main/java/com/adaptris/core/management/config/NashornChecker.java, interlok-core/src/main/java/com/adaptris/core/services/ScriptingService.java, interlok-core/src/main/java/com/adaptris/core/services/ScriptingServiceImp.java, interlok-core/src/main/java/com/adaptris/core/util/ObjectScanner.java, interlok-core/src/main/java/com/adaptris/core/util/ScriptingUtil.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.core.management.config.ConfigurationChecker, interlok-core/src/test/java/com/adaptris/core/management/config/NashornCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/services/EmbeddedScriptingServiceTest.java, interlok-core/src/test/java/com/adaptris/core/services/ScriptingServiceTest.java, interlok-core/src/test/java/com/adaptris/core/util/ObjectScannerTest.java, interlok-core/src/test/java/com/adaptris/core/util/ScriptingUtilTest.java
Since the nashorn scripting engine is deprecated in java 11 and due for removal in Java 17 we need to have some method whereby we notify people that their config is going to break.
- Refactor out graal / nashorn detection into a separate utility class
- Add a generic "object scanner" so that we can parse out ScriptingService implementations out the Adapter tree
- Add a Configuration Checker implementation
There is now a new __Nashorn Scripting Engine Check__ being reported on so if you have a scripting service impl (probably `embedded-scripting-service`)  that depends on nashorn because of any of the following reasons 
- The language is `nashorn`
- The language is one of `"js", "JS", "JavaScript", "javascript","ECMAScript", "ecmascript"` but graal js is not available
A configuration …
=> INTERLOK-3776 nashorn config checker

interlok-core/src/main/java/com/adaptris/core/CoreConstants.java, interlok-core/src/main/java/com/adaptris/core/DefaultSerializableMessageTranslator.java, interlok-core/src/test/java/com/adaptris/core/DefaultSerializableMessageTranslatorTest.java
Service Tester cannot handle Excel files with a file-payload-provider in a test-case. This is due to serializable message, et al. all only handling strings.
The DefaultSerializableMessageTranslator will now perform an Base64 decode to byte[] iff ContentEncoding is the string "BASE64".
This will allows any binary file to be used in the service tester when using a file payload.
To test this, follow the instructions on the [original ticket](https://adaptris.atlassian.net/browse/INTERLOK-3713).
=> INTERLOK-3713 Decode base64 data

interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/core/management/Constants.java, interlok-core/src/main/java/com/adaptris/core/management/ShutdownHandler.java, interlok-core/src/main/java/com/adaptris/core/management/UnifiedBootstrap.java, interlok-core/src/test/java/com/adaptris/core/management/AdapterConfigManagerTest.java, interlok-core/src/test/java/com/adaptris/core/management/BootstrapPropertiesTest.java, interlok-core/src/test/java/com/adaptris/core/management/ShutdownHandlerTest.java
ShutdownHandler has a hard-coded timeout (before it decides to force kill) of 30 seconds. This should be configurable based on the existing `operationTimeout` flag that contains startup.
- Moved the private constant from UnifiedBootstrap into Constants.
- Added a helper method getOperationTimeout() to BootstrapProperties since we want to have a floor for the value so that it's positive.
- Use getOperationTimeout() in both UnifedBootstrap + ShutdownHandler
- Add logging to that effect.
- Add tests for BootstrapProperties
The shutdown handler now obeys a configurable timeout.
- Modify your bootstrap.properties with `operationTimeout=3000` (3 seconds timeout).
- Start Interlok
```
TRACE [SimpleBootstrap] [c.a.c.m.UnifiedBootstrap.tryStart()] [{}] Start operationTimeout : 3 seconds
```
- …
=> INTERLOK-3818 Shutdown Operation Timeout now configurable

interlok-core-apt/src/main/java/com/adaptris/annotation/GenerateBeanInfo.java, interlok-core-apt/src/main/java/com/adaptris/annotation/InterlokAlias.java, interlok-core-apt/src/main/java/com/adaptris/annotation/InterlokLicence.java, interlok-core-apt/src/main/java/com/adaptris/taglet/ConfigTaglet.java, interlok-core-apt/src/main/java/com/adaptris/taglet/LicenseTaglet.java, interlok-core/src/main/java/com/adaptris/core/NullService.java
Taglets basically change between JVM versions (such that 11 broke us and we can't go back). If we switch to using documented annotations then they still present themselves in javadocs, but we *could* go back to java 8.
- Add `InterlokAlias` and `InterlokLicence` as annotations inside core-apt
- Add those annotations to `NullService`; and removed the `@config` annotation.
- Marked ConfigTaglet and LicenseTaglet as deprecated though I'm unsure if this will ever manifest itself IRL.
For NullService javadocs you should see something like this 
```
@InterlokAlias("null-service")
@InterlokLicence(NONE)
@ComponentProfile(summary="A NO-OP service",
tag="service")
public class NullService
extends ServiceImp
Null implementation of Service.
```
`./gradlew javadoc` and then view the javadocs …
=> INTERLOK-3775 annotations not taglets

interlok-core/src/main/java/com/adaptris/core/ChannelRestartProduceExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/NullProduceExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/ProduceExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/ProduceExceptionHandlerImp.java, interlok-core/src/main/java/com/adaptris/core/RestartProduceExceptionHandler.java, interlok-core/src/main/java/com/adaptris/core/WorkflowImp.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsTransactedWorkflow.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/interlok/junit/scaffolding/ExampleWorkflowCase.java
We have already deprecated the restart-produce-exception-handler because it causes more problems than it solves. Currently there are only 3 implementations; one of them being a NullProduceExceptionHandler. One of last two has been deprecated which leaves the channel-restart-produce-exception-handler.
* Add annotations, with messages and removal version info
* Update unit test
=> INTERLOK-3330 Deprecate ProduceExceptionHandler

interlok-core/src/test/java/com/adaptris/core/util/XmlHelperTest.java
One of the tests in XmlHelperTest was failing due to a line ending mismatch.
Update the example XML so that the line endings are consistent.
The unit tests and `gradle check` should now complete successfully.
Run `gradle check` - I've had success on both Windows and Linux.
=> Update example XML in XmlHelperTest

interlok-core/src/main/java/com/adaptris/core/runtime/MessageDigestErrorEntry.java, interlok-core/src/test/java/com/adaptris/core/runtime/MessageDigestErrorEntryTest.java
The failed message stacktrace are not retrieved with the failed messages when using jolokia.
It seems that Jolokia does not work well with getStackTrace as stackTrace a special word.
Add a new getter that can be used by jolokia to get the message error stackTrace
Add test assertions for the new getter
We can now get the stackTrace when using jolokia
- Build interlok-core.jar from this branch and use it.
- Start a new instance of interlok with interlok-jolokia (https://interlok.adaptris.net/interlok-docs/#/pages/advanced/advanced-jolokia):
- interlok-jolokia and its dependencies in the classpath
- Jolokia management component enabled: managementComponents=jolokia
- Make sure the interlok instance generate some errors. You can use the example config in …
=> INTERLOK-3806 Add a new getter that can be used by jolokia to get the message error stackTrace

interlok-common/src/main/java/com/adaptris/interlok/resolver/FileResolver.java, interlok-common/src/test/java/com/adaptris/interlok/resolver/FileResolverTest.java
The tests all passed in Unix land, but not on dev machines running Windows.
Catch the opporation not supported exception when trying to get POSIX permissions and just return an empty String. Then update the unit test to skip resolving the permissions.
No change for end user, but devs using Windows should now not experience test failures.
Run the unit tests, specifically FileResolverTest.
=> INTERLOK-3828 POSIX permissions aren't supported on Windows

interlok-common/src/test/java/com/adaptris/interlok/resolver/FileResolverTest.java
Foolishly thought there was only 1 test failure, because gradle said there was only 1 test failure, not realising that the subsequent check just didn't happen.
Remove unnecessary code.
No change for end user but tests are successful for developers.
`gradle build` (optional `clean` first).
=> INTERLOK-3828 Remove unnecessary test

interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java
If you use startAdapterQuietly =true in your bootstrap.properties then any failure will be reported as a stack trace.  Problem is if you don't set this flag, then any errors are not reported.
Simply made sure the bootstrap.start() is wrapped in a try/catch and any error reported.
=> INTERLOK-1270

interlok-boot/src/main/java/com/adaptris/interlok/boot/InterlokLauncher.java
This is a PR that alleviates the symptom of #782 (that's the motivation).
Makes the scenario described by #782 more predictable (it doesn't solve it) by making the jars that are added by the spring-boot-classloader are ordered alphabetically vis String.compareTo rather than leaving it to the order returned by .listFiles() which may not be.
Did not make the utlimate List<Archive> (that is used by spring-boot-loader) a Treeset, because making the Archives sorted might have additional ramifications we don't understand. So, for a given directory, _ensure that the list of jar files is sorted alphabetically only_; the other behaviour is left as-is.
Running against the docker image defined in the issue you now get, which resolves the specific symptom.
```
+ exec java -Xms488m -Xmx488m …
```
=> Force interlok-boot to resolve files alphabetically for consistency

interlok-common/src/main/resources/META-INF/services/com.adaptris.interlok.resolver.Resolver, interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageImp.java, interlok-core/src/main/java/com/adaptris/core/MultiPayloadAdaptrisMessageImp.java, interlok-core/src/main/java/com/adaptris/core/util/InputFieldExpression.java, interlok-core/src/test/java/com/adaptris/core/util/InputFieldExpressionTest.java
Fields are marked as resolvable which means they can be configured such that we resolve them on a per-message basis. In that situation we can't preempt performance improvements (like creating a queue on start() during Producer lifecycle. 
This helper allows us to determine if a field is an expression so that components can decide whether to potentially improve performance by pre-declaring high cost items if they aren't going to change during the component lifecycle.
- Removed a duplicate resolver from META-INF/services
- Renamed some constants in AdaptrisMessageImp + MultiPayloadMessage and made them public.
- Added InputFieldExpression with a static method.
In this situation things like environment variables + system properties are considered expressions since we have to make use of the …
=> Add a InputFieldExpressionHelper for determining when config truly needs to be dynamic

interlok-core/src/main/java/com/adaptris/core/ConfiguredConsumeDestination.java, interlok-core/src/main/java/com/adaptris/core/ConfiguredDestination.java, interlok-core/src/main/java/com/adaptris/core/ConfiguredProduceDestination.java, interlok-core/src/main/java/com/adaptris/core/ConsumeDestination.java, interlok-core/src/main/java/com/adaptris/core/ConsumeDestinationImp.java, interlok-core/src/main/java/com/adaptris/core/ExceptionDestination.java, interlok-core/src/main/java/com/adaptris/core/FormattedMetadataDestination.java, interlok-core/src/main/java/com/adaptris/core/MarshalledClassDestination.java, interlok-core/src/main/java/com/adaptris/core/MessageDrivenDestination.java, interlok-core/src/main/java/com/adaptris/core/MetadataDestination.java, interlok-core/src/main/java/com/adaptris/core/ProduceDestination.java, interlok-core/src/main/java/com/adaptris/core/XpathProduceDestination.java, interlok-core/src/main/java/com/adaptris/core/common/FileParameter.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsReplyToDestination.java, interlok-core/src/main/java/com/adaptris/core/services/aggregator/ConsumeDestinationFromMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/aggregator/ConsumeDestinationGenerator.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/ReadMetadataFromFilesystem.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/WriteMetadataToFilesystem.java, interlok-core/src/test/java/com/adaptris/core/management/config/DeprecatedConfigurationCheckerTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/ReadMetadataFromFilesystemTest.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/WriteMetadataToFilesystemTest.java
It looks as though we missed a deprecation annotation in core's `FileParameter` class that uses a Destination object. Then, when it was removed from the code in 4.0, no one was warned. It also means our transform to help with updating doesn't work very well.
Add deprecation annotations to destinations and their (missed) usages.
There should now be warnings for deprecated destination objects where there wasn't before. This then allows the user to fix the warnings before attempting to use the config in a v4 adapter.
Have an adapter configuration that uses destinations, specifically `FileParameter` - in a v3 adapter there should now be deprecation warnings, which highlight what to change for v4 - making said changes should allow the config to work in a v4 adapter.
=> bug/INTERLOK-3846 - deprecation annotation for destination objects

interlok-core/src/main/java/com/adaptris/core/http/jetty/BasicJettyConsumer.java
Lazy initialisation of handler map isn't suitable in high load environments since there is a chance of thread contention vis a vis state.
Add new initialiseHandlers() method which removes the if null detection so that the handlers are no longer lazily initialised on first request.
No configuration change
Bug fix
=> JETTY : Initialise handlers in init() method not lazily

interlok-core/src/main/java/com/adaptris/sftp/SftpClient.java, interlok-core/src/main/java/com/adaptris/sftp/SftpClientLogger.java, interlok-core/src/test/java/com/adaptris/core/fs/FsMessageConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/ftp/FtpConnectionCase.java, interlok-core/src/test/java/com/adaptris/core/ftp/FtpRecursiveConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/ftp/SftpExampleHelper.java, interlok-core/src/test/java/com/adaptris/core/ftp/StandardSftpConnectionTest.java, interlok-core/src/test/java/com/adaptris/filetransfer/FtpCase.java, interlok-core/src/test/java/com/adaptris/sftp/SftpClientLoggerTest.java, interlok-core/src/test/java/com/adaptris/sftp/test/TestSftp.java, interlok-core/src/test/resources/default-test.properties.template, interlok-core/src/test/resources/unit-tests.properties.template
Resolves #832 
If `ChallengeResponseAuthentication` is set to true in OpenSSH+Linux _and_ PAM is not reconfigured, then it is functionally equivalent to _password_ authentication (since PAM will just check the unix users password). So, realistically this is not true keyboard-interactive support since there's no way to programatically "ask the user" to respond to the server's challenge. However, it will fix the situation where OpenSSH is configured something like this, but with no additional PAM changes.
```
PasswordAuthentication no
KbdInteractiveAuthentication yes
ChallengeResponseAuthentication yes
```
Add a `SessionWrapper` to SftpClient which and private implementations that handle the publickey, keyboard-interactive, and password portions of SSH Authentication.
Add a …
=> Add keyboard-interactive shim to SftpClient

.gitignore, build.gradle
If you're an eclipse user then you often get a spurious error message about a missing `build/version` file. The problem goes away if you either compile on the commandline (thus generating the file) or in fact do a eclipse clean all...
The reason for this is that generating the version file is part of the sourceset definition, which it doesn't need to be.
I'm annoyed enough that I fixed the problem.
- Create a new generateVersionFile task that 
- generateVersionFile uses WriteProperties rather than ant.propertyFile()
- Add a .gitignore for `**/adaptris-version`
Note that the outputfile could write directly to the right place (classDir or where the resources end up) : `outputfile=file(processResources.destinationDir.getCanonicalPath() + '/META-INF/adaptris-version')` but this causes a …
=> Don't use sourceSets to create the version.

interlok-core/src/main/java/com/adaptris/core/SaferXMLResolver.java, interlok-core/src/main/resources/META-INF/services/com.adaptris.interlok.resolver.Resolver, interlok-core/src/test/java/com/adaptris/core/resolver/SaferXMLResolverTest.java
What if the resolved data isn't safe for XML? It should be escaped, or in this case, enclosed in CDATA tags.
Add new resolver that will wrap the resolved data in CDATA tags.
(Hopefully) the user can now include whatever they want when resolving into an XML document.
[Sample config](https://github.com/adaptris/interlok-json/files/7821836/adapter.xml.txt) that will resolve metadata and insert in into the XML payload. Used in combination with the [new JSON resolver](https://github.com/adaptris/interlok-json/pull/284).
NB The config will need updating to use `%asCDATA{...}`
=> interlok-2752 Add new XML resolver

interlok-core/src/main/java/com/adaptris/core/AdapterStateSummary.java, interlok-core/src/main/java/com/adaptris/core/RandomIntervalPoller.java, interlok-core/src/main/java/com/adaptris/core/event/LicenseExpiryWarningEvent.java, interlok-core/src/main/java/com/adaptris/core/jms/JmsProducerImpl.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/DatetimeStatementParameter.java, interlok-core/src/main/java/com/adaptris/core/services/jdbc/types/DateColumnTranslator.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/DateFormatBuilder.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/compare/CompareTimestamps.java, interlok-core/src/main/java/com/adaptris/ftp/ApacheFtpClientImpl.java, interlok-core/src/main/java/com/adaptris/transform/MappingUtils.java, interlok-core/src/main/java/com/adaptris/util/text/DateFormatUtil.java, interlok-core/src/test/java/com/adaptris/util/text/DateFormatUtilTest.java
```java
SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
Date d = format.parse("2021-08-18");
```
That string with that format will _parse_ but the date parsed won't be 18th August 2021. It'll be some time in 2020. This is because SimpleDateFormat is by default lenient and it has accepted the first 8 characters as the date.
- Add a strictFormatter() static method to DateFormatUtil
- Rather than creating a new SimpleDateFormat for every attempt to parse, make it a static ThreadLocal list of formatters in DateFormatUtil
- Where appropriate force delegation to the new strictFormatter() method rather than new SimpleDateFormat(). 
- This is generally where it's obvious that we're going to use the `parse` method.
- Add a new explicit test to show difference between lenient/strict in …
=> Force SimpleDateFormat where used to be strict

interlok-core/src/main/java/com/adaptris/core/fs/CompositeFileFilter.java, interlok-core/src/main/java/com/adaptris/core/fs/SizeBasedFileFilter.java, interlok-core/src/test/java/com/adaptris/core/fs/SizeBasedFilterTest.java
If you want a composite file filter you can have the string `SizeGTE=<some number in bytes>__@@__Regex=.*\.xml` but it's hard to figure out the number of bytes, who remembers that 1048760 is 10Megabytes?
It would be easier to have a human readable form of the bytes.
Since SizeBasedFilter takes a String argument we can take a human readable form and automagically convert it into the correct number of bytes.
Based on https://stackoverflow.com/a/52565585 
- 10G is transformed into 10 gigabytes
- 10M is transformed into 10 megabytes etc.
- Only the first char of the specifier counts, so 10MB = 10M
- Uppercase for the unit specifier so 10m == 10Megabytes.
- If no specifier (or an invalid one) is included, then defaults to bytes
- Has supports up to Yottabytes (which is largely irrelevant) to …
=> Add support for human readable sizes when creating size filters

interlok-core/src/main/java/com/adaptris/core/config/ConfigPreProcessors.java, interlok-core/src/main/java/com/adaptris/core/management/BootstrapProperties.java, interlok-core/src/main/java/com/adaptris/util/URLString.java
If you configure an adapter config file in your bootstrap.properties that does not exist, then you end up with a null pointer.
* Log error message if there's an exception
* Better handler the protocol of the config URL - this is what was causing the null pointer exception because apparently the protocol cannot be null
A more useful error message, and some indication of what went wrong during startup.
Delete your adapter.xml configuration and then start the adapter.
=> INTERLOK-2866 More useful error message with no config

.lgtm.yml, build.gradle, interlok-common/src/main/java/com/adaptris/interlok/resolver/FileResolver.java, interlok-core/src/main/java/com/adaptris/core/SharedComponent.java, interlok-core/src/main/java/com/adaptris/core/fs/FsHelper.java, interlok-core/src/main/java/com/adaptris/core/ftp/FtpRecursiveConsumer.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStore.java, interlok-core/src/main/java/com/adaptris/core/jdbc/JdbcService.java, interlok-core/src/main/java/com/adaptris/core/jdbc/ProxySqlConnection.java, interlok-core/src/main/java/com/adaptris/core/jms/jndi/BaseJndiImplementation.java, interlok-core/src/main/java/com/adaptris/core/jmx/JmxConnection.java, interlok-core/src/main/java/com/adaptris/core/services/ReadFileService.java, interlok-core/src/main/java/com/adaptris/core/services/dynamic/ServiceFromDatabase.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/AddFormattedMetadataService.java, interlok-core/src/main/java/com/adaptris/core/transform/schema/XmlSchemaValidatorImpl.java, interlok-core/src/main/java/com/adaptris/jdbc/connection/FailoverDataSource.java
https://lgtm.com/projects/g/adaptris/interlok/alerts/?mode=list has 33 alerts all around
`path-injection, xxe, jndi-injection, sql-injection, tainted-format-string` which are all ignorable in this context.
- Add SuppressWarning annotations where required.
- Attempt to fix lgtm double reporting (it's reporting on src/main/java && src/main/generated); this might not work
No Change
Once merged, check the alerts in lgtm; I checked the analysis in LGTM and that is correct.
=> Add LGTM suppressions.

interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java
StartAdapterQuietly = false would exit the JVM when a runtime exception would occur during start-up in the past.  But 1270 changes this behaviour, making startAdapterQuietly pointless.
Backed out 1270 from the CmdLineBootstrap class.
Previous behaviour of JVM exit has been re-introduced.
=> Backed out INTERLOK-1270. 

gradle/owasp-exclude.xml
CVE-2022-33915 refers specifically to a hotfix produced by AWS for log4j. Basically their mitigation for log4jshell is broken.  I don't see why they can't narrow the regexp to match log4j-cve-2021-44228-hotpatch-1.3-5
directly
Add suppression to ./gradle/owasp-exclude.xml
Downstream builds are no longer broken if they have a dependency on log4j.
`./gradlew dependencyCheckAnalyze` without the suppression.
`./gradlew dCAn` with the suppression.
=> build: mark CVE-2022-33915 as a false positive

gradle/owasp-exclude.xml
Jettison-1.2 & XStream-1.4.19 marked with HIGH vulns > 7.5
Jettison is required because we use XStream to round-trip JSON but 1.3+ is marked as incompatible with XStream.
XStream is the cornerstone of config, so we have to suppress their DoS CVEs
Ref: http://x-stream.github.io/json-tutorial.html
Ref: http://x-stream.github.io/download.html#optional-deps
- Add exclusions in for CVE-2022-40149 + CVE-2022-40150 for jettison
- Add exclusions for CVE-2022-40151 -> CVE-2022-40156 for xstream
- `gradle dependencyCheckAnalyze` now works
- `gradle dependencyCheckAnalyze` now works for build-parent.
- Run `gradle dCAnalyze` without the exclusions
- Run `gradle dCAnalyze` with the exclusions
=> owasp: add exclusion for jettison / xstream

interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageFactory.java, interlok-core/src/main/java/com/adaptris/security/password/SeededAesPbeCrypto.java, interlok-core/src/test/java/com/adaptris/core/AdaptrisMessageFactoryTest.java, interlok-core/src/test/java/com/adaptris/security/TestPassword.java, interlok-core/src/test/java/com/adaptris/security/password/PasswordTest.java, interlok-core/src/test/java/com/adaptris/security/password/SeededAesPbeCryptoTest.java
In the event that you wish to enforce certain default behaviours (i.e. storing the message in an opaque blob where `getInputStream()/getOutputStream()` returns a pointer to a remote blob (perhaps an S3 location) you have to explicitly configure a message factory on _every consumer_ in _every workflow_.
All consumers ultimately delegate to `AdaptrisMessageFactory.defaultIfNull(AMF)` to find the correct message factory to use which means that we can control the default message factory by injecting the correct thing into that static method.
- No additional configuration is done to the message factory, so it assumes that it is pre-configured (e.g. if you had an s3-message-factory it would already be configured with the correct credentials etc).
- The side effect of no config is that if you …
=> Control the default message factory and UID associated with messages via system properties.

interlok-core/src/main/java/com/adaptris/core/services/ResolveExpressionService.java, interlok-core/src/test/java/com/adaptris/core/services/ResolveExpressionServiceTest.java
Interlok has never handled basic string manipulation very well.  It's also one of the most requested features. 
I've added a service that will allow you to specify a string which may include resolvable expressions which will be calculated at runtime.
=> INTERLOK-3904 Resolve service added.

gradle/owasp-exclude.xml
CVE-2022-45685 / CVE-2022-45693 need to be excluded because jettison is required by XStream to round trip JSON, and we may not be upgraded to jettison-1.5.3
Updated owasp-exclude.xml
dependencyCheckAnalyze should now pass if you are referring to 4.6.0-RELEASE
Run dependencyCheckAnalyze on a project that uses interlok-build-parent before merging this branch; it should fail, because we refer to jettison-1.2 in the dependencies && interlok-core:4.6.0-RELEASE
Modify your local build.gradle
```
dependencyCheck.suppressionFiles.add("https://raw.githubusercontent.com/adaptris/interlok/jettison-cve/gradle/owasp-exclude.xml")
```
dependencyCheckAnalyze should now pass.
=> OWASP: jettison CVEs

gradle/owasp-exclude.xml
commons-net is already @ 3.9.0 which doesn't have the vuln (CVE-2021-37533), the other commons jar references seem to be a false positive regexp mismatch or something.
Updated owasp-exclude.xml
Removes this logging when you run dependencyCheckAnalyze.
```
commons-beanutils-1.9.4.jar (pkg:maven/commons-beanutils/commons-beanutils@1.9.4, cpe:2.3:a:apache:commons_beanutils:1.9.4:*:*:*:*:*:*:*, cpe:2.3:a:apache:commons_net:1.9.4:*:*:*:*:*:*:*) : CVE-2021-37533
commons-codec-1.15.jar (pkg:maven/commons-codec/commons-codec@1.15, cpe:2.3:a:apache:commons_net:1.15:*:*:*:*:*:*:*) : CVE-2021-37533
commons-collections-3.2.2.jar (pkg:maven/commons-collections/commons-collections@3.2.2, cpe:2.3:a:apache:commons_collections:3.2.2:*:*:*:*:*:*:*, cpe:2.3:a:apache:commons_net:3.2.2:*:*:*:*:*:*:*) : …
```
=> owasp: exclude commons-net CVE from commons jars

gradle/owasp-exclude.xml
commons-net is already @ 3.9.0 which doesn't have the vuln, the other commons jar references seem to be a false positive regexp mismatch or something.
Some remaining commons jars from https://github.com/adaptris/interlok/pull/1056
Updated owasp-exclude.xml
=> owasp: exclude commons-net CVE from commons-jars

.github/workflows/codeql-analysis.yml
Because code-ql is not configured in the same way as lgtm is/was
modify codeql-analysis so that we enable alert-suppressions and correspondingly dismiss the alerts.
c.f. https://quotidian-ennui.github.io/blog/2023/02/24/codeql-java/
No effect on the user.
The existing 8 alerts that were already suppressed by LGTM are now suppressed again in https://github.com/adaptris/interlok/security
=> feat: add alert-suppression capabilities

interlok-core-apt/build.gradle, interlok-core/build.gradle
javax.el 3.0.1 reports CVE-2021-28170; it's a medium vuln but is sometimes reported
- 4.0.2 only contains the com.sun classes and no javax.el clases. 
- 5.0.0M1 is a likely switch to jakarta.el namespace.
Bump the dependency
No change, tests pass
No change for the user.
=> deps: switch to jakarta.el dependency

interlok-core/src/main/java/com/adaptris/core/services/metadata/AddTimestampMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/timestamp/LastMessageTimestampGenerator.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/timestamp/OffsetTimestampGenerator.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/timestamp/TimestampGenerator.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/AddTimestampMetadataServiceTest.java
So the offset field used by the AddTimestampMetadataService can be validated against a regex pattern that makes sure it adheres to the ISO8601 standard. This also includes validation in the UI and when the service is initialised.
AddTimestampMetadataService class
AddTimestampMetadataServiceTest class
OffsetTimestampGenerator class
- [n/a] Added javadocs for most classes and all non-trivial methods
- [n/a] Added supporting annotations (like @XStreamAlias / @ComponentProfile)
- [n/a] Added DefaultValue annotation when there is a default value (e.g. @DefaultValue('true'))
- [n/a] Checked that @NotNull and @NotBlank annotations have a meaningful message when appropriate.
- [n/a] Remove any config/license annotations
- …
=> Interlok 521 add regex validation for offset field

interlok-core/src/main/java/com/adaptris/core/http/client/net/HttpRequestServiceImpl.java, interlok-core/src/test/java/com/adaptris/core/http/client/net/HttpRequestServiceTest.java
So we can expose the timeout options that are available in the standard http producer.
Updated the class HttpRequestServiceImp so it gives the timeout options in the UI and when creating a StandardHttpProducer object we pass in the timeout values that have been set.
Also added a new unit test that tests that the read timeout will throw an exception if it is exceeded.
- [n/a] Added DefaultValue annotation when there is a default value (e.g. @DefaultValue('true'))
- [n/a] Checked that @NotNull and @NotBlank annotations have a meaningful message when appropriate.
- [n/a] Remove any config/license annotations
The end user is now able to choose and swet connect and read timeout durations when using this service.
You can …
=> Interlok 4071 expose timeout options

gradle/owasp-exclude.xml, interlok-common/build.gradle, interlok-common/src/main/java/com/adaptris/core/management/webserver/JettyServerManager.java, interlok-common/src/main/resources/com/adaptris/core/management/webserver/jetty-failsafe.xml, interlok-common/src/main/resources/com/adaptris/core/management/webserver/jetty-webdefault-failsafe.xml, interlok-common/src/test/java/com/adaptris/core/management/webserver/JettyServerBuilder.java, interlok-core/build.gradle, interlok-core/src/main/java/com/adaptris/core/http/jetty/EmbeddedConnection.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/HttpConnection.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/HttpsConnection.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/LoginServiceProxy.java, interlok-core/src/main/java/com/adaptris/core/management/jetty/FromProperties.java, interlok-core/src/main/java/com/adaptris/core/management/jetty/FromXmlConfig.java, interlok-core/src/main/java/com/adaptris/core/management/jetty/ServerBuilder.java, interlok-core/src/main/java/com/adaptris/core/management/jmx/SimpleCallbackHandler.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/HttpConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/HttpsConsumerTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/JettyLoginProxyTest.java, interlok-core/src/test/java/com/adaptris/core/management/jetty/JettyMgmtComponentTest.java, interlok-core/src/test/resources/jetty-configure.dtd, interlok-core/src/test/resources/jetty/jetty.xml
Upgrade Interlok to Jetty 10
- Mostly upgraded dependencies and the jetty xml files
- Remove the RewriteHandler to forward the old UI context /adapter-web-ui to /interlok
- JettyServerManager reconfigureWar now set the rootwar classloader with the current classloader to be able to load jetty's classes.
- Upgrade all the jetty related classes to fix compile issues.
- Use lombok in some of the jetty classes
- Fix tests.
- Update javadocs.
- Remove some warnings.
Interlok is using jetty 10.
No visible impact on the end user.
This PR build should pass.
Use the jars from this branch and the right jetty 10 dependencies.
```
interlokRuntime ("org.eclipse.jetty:jetty-alpn-client:$jettyVersion")
interlokRuntime ("org.eclipse.jetty:jetty-alpn-java-client:$jettyVersion")
interlokRuntime …
```
=> INTERLOK-4081 Upgraded to jetty10

interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStore.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/RetryStore.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/AcknowledgeService.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/Constants.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/JdbcRetryStore.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/JdbcRetryStoreEntry.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/RetryMessagesService.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/RetryServiceImp.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/StoreMessageForRetryService.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/InMemoryRetryStore.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryFromJettyTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryStoreTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/AcknowledgeServiceTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/JdbcRetryStoreTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/RetryMessagesServiceTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/RetryServiceImpTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/StoreMessageForRetryServiceTest.java, interlok-core/src/test/resources/unit-tests.properties.template
To replicate the JDBC retry store and it's related set of services from v2 in v4
Updated the underlying RetryStore interface with some new required methods.
Updated existing classes that implemented that interface with the new methods but all have empty imps for now.
Added the new JdbcRetryStore class and it's related services.
Adding unit test classes too.
- [n/a] Check the gradle build file to make sure the dependencies section is more explicit "implementation/api".
A new set of services and a JDBC retry store which can now be used.
=> Interlok 4134 jdbc retrystore v4

interlok-core/build.gradle, interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStore.java, interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/RetryStore.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/AcknowledgeService.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/Constants.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/JdbcRetryStore.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/JdbcRetryStoreEntry.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/RetryMessagesService.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/RetryServiceImp.java, interlok-core/src/main/java/com/adaptris/core/jdbc/retry/StoreMessageForRetryService.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/InMemoryRetryStore.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryFromJettyTest.java, interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryStoreTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/AcknowledgeServiceTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/JdbcRetryStoreTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/RetryMessagesServiceTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/RetryServiceImpTest.java, interlok-core/src/test/java/com/adaptris/core/jdbc/retry/StoreMessageForRetryServiceTest.java, interlok-core/src/test/resources/retry-store.properties, interlok-core/src/test/resources/unit-tests.properties.template
To replicate the JDBC retry store and it's related set of services from v2 in v5
Updated the underlying RetryStore interface with some new required methods.
Updated existing classes that implemented that interface with the new methods but all have empty imps for now.
Added the new JdbcRetryStore class and it's related services.
Adding unit test classes too.
- [n/a] Check the gradle build file to make sure the dependencies section is more explicit "implementation/api".
A new set of services and a JDBC retry store which can now be used.
=> Interlok 4134 jdbc retrystore

gradle/owasp-exclude.xml
OWASP dependency check is failing.
Suppress CVE-2023-39017 as it is only for quartz-jobs-2.3.2.jar and org.quartz.jobs.ee.jms.SendQueueMessageJob.execute which we are not using.
No change for the end user
OWASP dependency check should pass.
=> INTERLOK-4156 CVE-2023-39017

interlok-core/src/main/java/com/adaptris/core/util/ManagedThreadFactory.java
The internal SecurityManager is deprecated for future removal.
We were using the SecurityManager to gain access to a ThreadGroup; however the default behaviour appears to return the current threads group, which doesn't need the SecurityManager at all.  So we have just removed the line to that class and get access to the current threads group manually.
No warnings about SecurityManager being deprecated.
nothing changes.
=> Removing the use of the internal security manager.

interlok-core/build.gradle
There is an issue with more recent versions of flyway  (8+ I think) where it needs extra jar for mysql and sqlserver (for licensing purposes).
The issue occurs if we use interlok-flyway and the UI at the same time and mysql or sqlserver.
We end up with two flyway-core.jar, one in the interlok lib dir and one in the webapp lib dir.
When the UI starts and load its spring config it will use its flyway-core.jar but will also find the mysql-flyway.jar that exists in the interlok lib dir.
This will cause some service discovery issue because of classloaders differences between the UI flyway-core.jar and the interlok mysql-flyway.jar:
```
java.util.ServiceConfigurationError: org.flywaydb.core.extensibility.Plugin: org.flywaydb.database.mysql.MySQLDatabaseType not a subtype
```
So we should …
=> INTERLOK-4187 Make flyway a dependency of interlok-core

.github/workflows/publish-3.12.yml, interlok-client-jmx/build.gradle, interlok-client/build.gradle, interlok-common/build.gradle, interlok-common/src/main/java/com/adaptris/core/management/webserver/JettyServerManager.java, interlok-common/src/main/resources/com/adaptris/core/management/webserver/jetty-failsafe.xml, interlok-core/build.gradle, interlok-core/src/main/resources/META-INF/templates/template-jetty.xml, interlok-logging/build.gradle
Fix CVE-2023-44487 and the jetty-failsafe.xml
Upgrade to jetty 9.4.53.v20231009 and fix jetty-failsafe.xml to not use the same id multiple times
Also bump log4j to 2.21.0 and slf4j to 1.7.36
No more vulnerability
The build should be successful and we should be able to start interlok with jetty enabled.
=> INTERLOK-4206 Upgrade to jetty 9.4.53.v20231009

interlok-core/src/main/java/com/adaptris/core/transform/MultiPayloadXmlTransformService.java, interlok-core/src/main/java/com/adaptris/core/transform/XmlTransformService.java, interlok-core/src/main/java/com/adaptris/util/text/xml/StxTransformerFactory.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XmlTransformerFactory.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XmlTransformerFactoryImpl.java, interlok-core/src/main/java/com/adaptris/util/text/xml/XsltTransformerFactory.java, interlok-core/src/test/java/com/adaptris/core/transform/MultiPayloadXmlTransformServiceTest.java, interlok-core/src/test/java/com/adaptris/core/transform/XmlTransformServiceTest.java, interlok-core/src/test/java/com/adaptris/util/text/XmlTransformerTest.java
To enable xml transform services to support string data input parameters(multipayload, file, constant, etc)
This is in part to help with the config upgrade tool that is being built.
**XmlTransformerFactory** - Interface has been updated to add two new methods and renaming of the exisitng ones so they are clear as to what they do. This is so the implementing classes can now support xsl's either passed as a url to a file(what it currently supports) and also xsl's being passed in as the input themselves.
**StxTransformerFactory
XmlTransformerFactory** - Updated to implement the new methods as mentioned above.
**XmlTransformerFactoryImpl** - abstract class updated to have common logic moved to here.
**XmlTransformService
MultiPayloadXmlTransformService** - Both updated so they now support …
=> Feature/interlok 4220 - Add input param support for xml transform services

interlok-core/src/main/java/com/adaptris/core/util/XmlHelper.java, interlok-core/src/test/java/com/adaptris/core/util/XmlHelperTest.java
We need an xml helper method that can do nodeToString with the XML Declaration
Add an option to nodeToString do add XML Declaration
Add a test
There is a new nodeToString method that can add the XML Declaration. The default behaviour of nodeToString  remain the same.
The build should pass.
=> INTERLOK-4243 add an option to nodeToString do add XML Declaration

interlok-core/src/main/java/com/adaptris/core/services/metadata/MetadataTarget.java, interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadToMetadataService.java, interlok-core/src/main/java/com/adaptris/core/services/mime/FlattenMimeParts.java, interlok-core/src/main/java/com/adaptris/core/services/mime/InlineMimePartBuilder.java, interlok-core/src/main/java/com/adaptris/core/services/mime/MimePartSelector.java, interlok-core/src/main/java/com/adaptris/core/services/mime/MimePartSelectorToMetadata.java, interlok-core/src/main/java/com/adaptris/core/services/mime/MultipartMessageBuilder.java, interlok-core/src/main/java/com/adaptris/core/services/mime/PartSelectorToMetadata.java, interlok-core/src/test/java/com/adaptris/core/services/metadata/PayloadToMetadataTest.java, interlok-core/src/test/java/com/adaptris/core/services/mime/MimePartSelectorToMetadataTest.java
We needed a way to select multiple mime parts and keep them without modifying the payload.
Add a new MimePartSelectorToMetadata. It works in a similar way as MimePartSelector but allows to select multiple mime and store them into metadata. The mime payload remains unchanged.
Add tests.
We have a new MimePartSelectorToMetadata service
The build and test should be successful.
This has already been tested in interlok-upgrade-tool.
=> INTERLOK-4285 Add MimePartSelectorToMetadata

interlok-core/build.gradle
When using flyway and mysql in the UI we now get an issue as we need flyway-mysql.jar in the lib dir but it’s not in the same class loader as flyway-core.jar and therefore we get a CNFE.
Make flyway a dependency of interlok-core so the UI doesn't need to import it into its war file and that won't cause a jar conflict when using interlok-flyway and will work when using flyway-mysql.jar.
Everything should work fine when using the UI with flyway and mysql
Build an instance of interlok with the interlok-core.jar from this branch and the UI for the related PR (https://github.com/adaptris/interlok-ui/pull/251) in interlok-ui project.
Add flyway-mysql.jar as a dependency and mysql-connector and it should work.
=> INTERLOK-4302 Make flyway a dependency of interlok-core

interlok-core/src/main/java/com/adaptris/core/BranchingServiceCollection.java, interlok-core/src/main/java/com/adaptris/core/CloneMessageServiceList.java, interlok-core/src/main/java/com/adaptris/core/Service.java, interlok-core/src/main/java/com/adaptris/core/ServiceCollectionImp.java, interlok-core/src/main/java/com/adaptris/core/ServiceImp.java, interlok-core/src/main/java/com/adaptris/core/ServiceList.java, interlok-core/src/main/java/com/adaptris/core/SharedComponent.java, interlok-core/src/main/java/com/adaptris/core/SharedServiceImpl.java, interlok-core/src/test/java/com/adaptris/core/BranchingServiceCollectionTest.java, interlok-core/src/test/java/com/adaptris/core/ServiceListTest.java, interlok-core/src/test/java/com/adaptris/core/SharedServiceTest.java
We would like the option to disable a service/list in a workflow, such that it's lifecycle methods do not execute and it will be skipped in the workflows execution..
Added an "enabled" boolean property to the Service interface.
Service lists now check that property when requesting each service to init/start/stop/close.  Additionally the flag is checked before the service is executed.
Because this new property uses a java.util.Boolean rather than a boolean, the value can be null.
You should therefore use the public method "enabled()" which returns a standard boolean, defaulting to true if not set.
We default to true in the Service interface just in case there are external service implementations that implement the Service interface instead of extending ServiceImp.
A new property named …
=> INTERLOK-4312 We can now enable/disable each service

interlok-core/src/main/java/com/adaptris/core/MultiPayloadAdaptrisMessageImp.java, interlok-core/src/test/java/com/adaptris/core/MultiPayloadAdaptrisMessageImpTest.java, interlok-core/src/test/resources/example-payload.txt, interlok-core/src/test/resources/unit-tests.properties.template
To Address a bug where when a multipayload message is created and we call the method
`public OutputStream getOutputStream(@NotNull String payloadId)` this was causing the Payload class to store a ByteArrayOutputStream against the variable 'stream' which meant that when you tried to update the payloads content logic in the payload() method was always setting the payload to the value originally stored against the variable 'stream'
Added a new unit test and supproting files to:
A. prove the bug existed(as the unit test was failing as expected)
B. to show the bug is now fixed as the unit test now passes.
I also implemented a small fix within the inner class Payload so we no longer store the two different data types and then have logic to decide which one to retrive as when the data is …
=> Bug/interlok 4325 - MultiPayloadAdaptrisMessage issue where original payload cannot be updated if content originated from an input stream.

interlok-core/src/main/java/com/adaptris/util/URLHelper.java
It's possible for our URLHelper to never timeout while fetching a remote resource.
Added timeouts for read and connect.
=> Making sure the URLConnection in the URLHelper can timeout.

interlok-core/src/main/java/com/adaptris/util/URLHelper.java
Any service using the URLHelper to fetch a remote resource could spin forever, never timing out.
This would cause a hang.
Simply added the read and connect timeouts defaulted to a sensible 30 seconds to the URLConnection  code in the URLHelper.
=> Added a timeout for the URLConnection in the URLHelper

interlok-core/src/main/java/com/adaptris/core/jms/SizeLimitedTextMessageTranslator.java, interlok-core/src/main/java/com/adaptris/core/runtime/ChannelManager.java, interlok-core/src/main/java/com/adaptris/core/runtime/ChannelManagerMBean.java, interlok-core/src/test/java/com/adaptris/core/jms/SizeLimitedTextMessageTranslatorTest.java, interlok-core/src/test/java/com/adaptris/core/runtime/AdapterManagerTest.java, interlok-core/src/test/java/com/adaptris/core/runtime/ChannelManagerTest.java
The health check component reports a failure if a single channel has not started, this is fine normally, but if you have a channel that is set to NOT start up, then this channel should be ignored.
This is the first step, by exposing the auto-start configuration on the channel through it's MBean.  We need this exposed as the healthcheck component uses the MBeans to check state.
Exposed the auto-start attribute through the Channels MBean interface and then the implementation in the ChannelManager.
=> Health check channel auto start

interlok-core/src/main/java/com/adaptris/core/services/RetryingServiceWrapper.java
We get a NPE when numRetries is not set in the RetryingServiceWrapper
Don't use numRetries property directly but used the method numRetries() that return the default value if null.
numRetries can be left empty without causing a NPE
Configure the RetryingServiceWrapper and leave numRetries.
Then, run that service and make sure it works fine.
=> INTERLOK-4422 Fix potential NPE when numRetries is not set
