- .travis.yml
- Install latest oracle8jdk
- Install JCE
- Install and Start haveged (because randomness was taking too long
without it)
- Change away from container based to allow sudo execution
> Update Travis to work with ant test

- adapter/src/main/java/com/adaptris/core/fs/FsConsumerMonitor.java
- adapter/src/main/java/com/adaptris/core/fs/FsConsumerMonitorMBean.java
- adapter/src/main/java/com/adaptris/core/runtime/AdapterComponentMBean.java
- adapter/src/main/java/com/adaptris/core/runtime/ConsumerMonitorImpl.java
- adapter/src/main/java/com/adaptris/core/runtime/ConsumerMonitorMBean.java
Allows other consumers to implement a monitor
> INTERLOK-2229 Generic Consumer Monitor MBean

- docs/adr/0002-add-default-implementations-to-componentlifecycle.md
- interlok-core/src/main/java/com/adaptris/core/ComponentLifecycle.java
https://github.com/adaptris/interlok/blob/feature/ADR-0002/docs/adr/0002-add-default-implementations-to-componentlifecycle.md
* Changes already applied to ComponentLifeCycle (it's a single file change)
* ./gradlew check works.
> Add default implementation to ComponentLifecycle

- interlok-core/src/main/java/com/adaptris/core/services/jdbc/SplittingXmlPayloadTranslator.java
- interlok-core/src/test/java/com/adaptris/core/services/jdbc/SplittingXmlPayloadTranslatorTest.java
- Add copy-metadata that defaults to false for backwards compat If true, then copies the original metadata into the child message; never copies object metadata, since the thing you do in the splitter is to produce it somewhere (which means you lose the object metadata)
- Made MaxRowsPerMessage an Integer
- Added NotNull messages for INTERLOK-2705
> INTERLOK-2703 Add copy-metadata flag

- interlok-core/src/main/java/com/adaptris/core/ftp/SftpAuthenticationWrapper.java
- interlok-core/src/test/java/com/adaptris/core/ftp/SftpAuthenticationWrapperTest.java
- Add configurable logging
- Change the exception message to say providers.
- Add tests.
> INTERLOK-2743 Add Logging to SftpAuthenticationWrapper

- interlok-core/src/main/java/com/adaptris/core/AdaptrisMessageConsumer.java
- interlok-core/src/main/java/com/adaptris/core/fs/FsConsumerImpl.java
- interlok-core/src/main/java/com/adaptris/core/ftp/FtpConsumerImpl.java
- interlok-core/src/main/java/com/adaptris/core/http/jetty/BasicJettyConsumer.java
- interlok-core/src/main/java/com/adaptris/core/jms/JmsConsumerImpl.java
- interlok-core/src/main/java/com/adaptris/core/jms/JmsPollingConsumerImpl.java
Fixed the javadoc warnings since the value tag needs to be fully qualified.
> Fix javadoc warnings

- interlok-core/src/main/java/com/adaptris/core/services/cache/CacheConnection.java
- interlok-core/src/main/java/com/adaptris/core/services/conditional/conditions/ExistsInCache.java
- interlok-core/src/test/java/com/adaptris/core/services/conditional/conditions/CacheConditionTest.java
Add exists in cache condition with tests.
> INTERLOK-2851 Add ExistsInCache condition

- docs/adr/0003-deprecate-dynamicservicelocator.md
- docs/adr/0004-remove-jndi-bindable-lookup-name.md
https://github.com/adaptris/interlok/blob/adr/INTERLOK-2872/docs/adr/0004-remove-jndi-bindable-lookup-name.md
> INTERLOK-2872 - Add record of why we would want to remove getLookupName

- interlok-core/src/main/java/com/adaptris/core/jms/AggregatingQueueConsumer.java
I don't have permissions to update the develop branch so here is a pull request to fix a type in an error msg which was initially raised by Juan.
> Corrected typo in error msg

- interlok-core/src/main/java/com/adaptris/core/security/SymmetricKeyCryptographyService.java
- interlok-core/src/main/java/com/adaptris/security/util/SecurityUtil.java
- modify the getAlgorithms to be fancy and give the type + provider as well.
> INTERLOK-2926 Call Security.addProvider in the constructor

- interlok-core/src/main/java/com/adaptris/core/jms/JmsConsumer.java
- interlok-core/src/test/java/com/adaptris/core/jms/JmsConsumerTest.java
JmsConsumer can now let the vendor implementation create the consumer if you configure it so.
> INTERLOK-1904

- interlok-core/src/main/java/com/adaptris/core/services/duplicate/CheckMetadataValueService.java
- interlok-core/src/main/java/com/adaptris/core/services/duplicate/DuplicateMessageRoutingService.java
- interlok-core/src/main/java/com/adaptris/core/services/duplicate/DuplicateMetadataValueService.java
- interlok-core/src/main/java/com/adaptris/core/services/duplicate/StoreMetadataValueService.java
- interlok-core/src/test/java/com/adaptris/core/services/duplicate/CheckMetadataValueServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/duplicate/DuplicateMessageRoutingServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/duplicate/StoreMetadataValueServiceTest.java
- Refactor code for testability
> Duplicate services coverage should easily be 100%

- interlok-core/src/main/java/com/adaptris/core/services/metadata/AddFormattedMetadataService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/AddMetadataService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/MapMetadataService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/MetadataValueBranchingService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/PayloadToMetadataService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/ReformatMetadata.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/RegexpMetadataQuery.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/RegexpMetadataService.java
- interlok-core/src/main/java/com/adaptris/core/services/metadata/WriteMetadataToFilesystem.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/AddFormattedMetadataServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/AddMetadataServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/CreateQueryStringFromMetadataTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/DateFormatBuilderWithOptionalFractionAndOffsetTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/FormDataToMetadataTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/MapMetadataServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/MetadataBranchingServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/PayloadToMetadataTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/TrimMetadataServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/services/metadata/XpathObjectMetadataServiceTest.java
Since, surely we must be able to 100% things that just are in memory...
> Aim for 100% Metadata services coverage

- interlok-core/src/main/java/com/adaptris/core/http/MetadataContentTypeProvider.java
- interlok-core/src/main/java/com/adaptris/core/http/ResourceAuthenticator.java
- interlok-core/src/main/java/com/adaptris/core/http/auth/ConfiguredUsernamePassword.java
- interlok-core/src/main/java/com/adaptris/core/http/auth/MetadataUsernamePassword.java
- interlok-core/src/main/java/com/adaptris/core/http/auth/ThreadLocalCredentials.java
- interlok-core/src/main/java/com/adaptris/core/http/auth/UserPassAuthentication.java
- interlok-core/src/test/java/com/adaptris/core/http/RequestParameterConverterServiceTest.java
- interlok-core/src/test/java/com/adaptris/core/http/ResourceAuthenticatorTest.java
- interlok-core/src/test/java/com/adaptris/core/http/auth/ThreadLocalCredentialsTest.java
- interlok-core/src/test/java/com/adaptris/core/http/auth/UsernamePasswordTest.java
* com.adaptris.core.http
* com.adaptris.core.http.auth
Found a bug in ResourceAuthenticator.ResourceTarget as a result of the tests...; lucky for us there aren't any actual authenitcators that interrogate the "scheme".
> Aim for 100% on supporting http packages

- .circleci/config.yml
Switch to using a machine based circleci build
- Include haveged
- Include mysql-server
- Change the checksum for dependencies to include interlok-core/build.gradle...
> Switch to using a machine based build.

- interlok-common/build.gradle
- interlok-core/build.gradle
- interlok-core/src/test/java/com/adaptris/core/http/jetty/ServletWrapperTest.java
Replace #257 since I did a lot of messing around with the circleci with that since it was an already open PR.
> Bump jetty to 9.4.21

- interlok-core/src/main/java/com/adaptris/core/management/CmdLineBootstrap.java
```
$ java -Dinterlok.bootstrap.debug=true -jar lib/interlok-boot.jar -configcheck
... (stuff skipped)
(Info) Log4j2Init.shutdown()
(Info) Stopping class org.apache.logging.log4j.core.appender.ConsoleAppender
(Info) Stopping class org.apache.logging.log4j.core.appender.RollingFileAppender
(Info) Stopping class com.adaptris.logging.jmx.log4j.JmxLogAppender
javax/activation/ActivationDataFlavor.class has possible duplicates
-> Found in jar:file:C%3a/adaptris/work/runtime/ant-nightly/lib/activation.jar!/javax/activation/ActivationDataFlavor.class
-> Found in jar:file:C%3a/adaptris/work/runtime/ant-nightly/lib/javax.activation-api.jar!/javax/activation/ActivationDataFlavor.class
javax/activation/CommandInfo.class has possible duplicates
-> Found in …
```
> On -configcheck print out poassible duplicates on the classpath.

- interlok-core/src/main/java/com/adaptris/core/AbstractMarshaller.java
- interlok-core/src/main/java/com/adaptris/core/AdapterStateSummary.java
- interlok-core/src/main/java/com/adaptris/core/RetryMessageErrorHandlerImp.java
- interlok-core/src/main/java/com/adaptris/core/XStreamMarshallerImpl.java
- interlok-core/src/main/java/com/adaptris/core/common/FileDataInputParameter.java
- interlok-core/src/main/java/com/adaptris/core/config/PreProcessingXStreamMarshaller.java
- interlok-core/src/main/java/com/adaptris/core/fs/FsImmediateEventPoller.java
- interlok-core/src/main/java/com/adaptris/core/http/auth/ThreadLocalCredentials.java
- interlok-core/src/main/java/com/adaptris/core/http/jetty/JettyAsyncWorkflowInterceptor.java
- interlok-core/src/main/java/com/adaptris/core/jms/ActiveJmsConnectionErrorHandler.java
- interlok-core/src/main/java/com/adaptris/core/jms/IntegerMetadataConverter.java
- interlok-core/src/main/java/com/adaptris/core/management/vcs/RuntimeVersionControlLoader.java
- interlok-core/src/main/java/com/adaptris/core/services/ScriptingServiceImp.java
- interlok-core/src/main/java/com/adaptris/core/services/splitter/MimePartSplitter.java
- interlok-core/src/main/java/com/adaptris/jdbc/connection/FailoverDataSource.java
- interlok-core/src/main/java/com/adaptris/util/GetServiceByName.java
- interlok-core/src/main/java/com/adaptris/util/datastore/SimpleDataStore.java
- interlok-core/src/test/java/com/adaptris/core/ExampleConfigCase.java
Mostly obvious;
-> GetServiceByName wasn't really used very much anyway (might be used in SAP)
-> AdaptrisMarshaller now has functional interfaces galore... probably could make a few of the methods default interfaces actually.
> Fix some of the actual sonarqube issues

- interlok-core/src/main/java/com/adaptris/core/Channel.java
- interlok-core/src/main/java/com/adaptris/core/ConfigComment.java
- interlok-core/src/main/java/com/adaptris/core/ServiceCollection.java
- interlok-core/src/main/java/com/adaptris/core/ServiceCollectionImp.java
- interlok-core/src/main/java/com/adaptris/core/Workflow.java
- interlok-core/src/main/java/com/adaptris/core/WorkflowImp.java
- interlok-core/src/test/java/com/adaptris/core/ChannelTest.java
- interlok-core/src/test/java/com/adaptris/core/ConfigCommentHelper.java
- interlok-core/src/test/java/com/adaptris/core/ExampleWorkflowCase.java
- interlok-core/src/test/java/com/adaptris/core/ServiceCollectionCase.java
- interlok-core/src/test/java/com/adaptris/core/ServiceListTest.java
- Add ConfigComment interface and test.
> INTERLOK-2990 Add ConfigComment interface

- docs/adr/0006-workflow-callback.md
https://github.com/adaptris/interlok/blob/adr/ADR-0006-workflow-callback/docs/adr/0006-workflow-callback.md
Once merged then it is : https://github.com/adaptris/interlok/blob/develop/docs/adr/0006-workflow-callback.md (until merged, this just has dummy content).
> ADR-0006 Add a callback to AdaptrisMessageListener.

- interlok-core/src/main/java/com/adaptris/core/interceptor/LoggingContextWorkflowInterceptor.java
- interlok-core/src/main/java/com/adaptris/core/services/AddExtendedLoggingContext.java
- interlok-core/src/main/java/com/adaptris/core/services/RemoveLoggingContext.java
- interlok-core/src/test/java/com/adaptris/core/interceptor/LoggingContextInterceptorTest.java
- interlok-core/src/test/java/com/adaptris/core/services/AddExtendedLoggingContextTest.java
- LoggingContextWorkflowInterceptor adds object metadata
- AddExtendedLoggingContext optionally adds metadata based on that
- RemoveLoggingContext switched to using list
> INTERLOK-3080 Extended Logging Context

- interlok-common/src/main/java/com/adaptris/interlok/cloud/RemoteBlobFilterWrapper.java
- interlok-core-apt/src/main/java/com/adaptris/annotation/InputFieldHint.java
- interlok-core/src/main/java/com/adaptris/core/fs/FsConsumerImpl.java
It will helps displaying a list of suggestions for the field value in the
UI.
> INTERLOK-2997 #comment  Add  implemts to InputFieldHint annotation.

- .github/workflows/gradle.yml
- .lgtm.yml
gradle build on push; github action.
> Github action for opensource components.

- interlok-core/src/main/java/com/adaptris/core/fs/AggregatingFsConsumer.java
- interlok-core/src/main/java/com/adaptris/core/ftp/AggregatingFtpConsumer.java
- interlok-core/src/main/java/com/adaptris/core/ftp/FtpConsumerImpl.java
Add @InputFieldHint(ofType = "java.io.FileFilter") on fileFilterImp to get the autocomplete in the UI.
> INTERLOK-3103 Add ofType=java.io.FileFilter

- interlok-core/src/main/java/com/adaptris/core/services/metadata/AddFormattedMetadataService.java
Add javadocs so that it displays in componet search. It already has a componentProfile.
> INTERLOK-3000 Add javadocs

- interlok-core/src/main/resources/META-INF/templates/template-bootstrap.properties
- interlok-core/src/main/resources/META-INF/templates/template-jetty.xml
- interlok-core/src/main/resources/META-INF/templates/template-log4j2.xml
- interlok-core/src/main/resources/META-INF/templates/template-webdefault.xml
When saving a new project; the UI should be able to save additional files into the `src/main/interlok/config` directory;
Add minimal files into META-INF/templates of interlok-core
No visible changes until INTERLOK-3194 is actioned.
Build `gradle jar` -> there should now be a `META-INF/templates` inside the jar file.
> INTERLOK-3194 Add template files

- interlok-common/src/main/java/com/adaptris/interlok/util/ResourceLocator.java
- interlok-common/src/test/java/com/adaptris/interlok/util/ResourceLocatorTest.java
There appear to be a lot of configuration out there that uses relative URLs (e.g. for loggingConfigUrl=`file://localhost/./config/log4j2.xml`) which is now broken because of the changes from https://github.com/adaptris/interlok/pull/437 
We need to be able to handle that kind of URL; since this isn't a breaking release.
Change the detection of local resources to be file or "null" based rather than uri.isAbsolute()
Add a new fileUrl local resolver that can cope with "relative" paths as part of the URL.
File URLs which are "relative" should now work : 
```
loggingConfigUrl=file://localhost./config/log4j2.xml
webServerConfigUrl=file://localhost/./config/jetty.xml
```
- Take an existing project (e.g.  https://github.com/adaptris-labs/build-parent-json-csv). Modify the bootstrap.properties so …
> INTERLOK-3219 copy with file://localhost/./config

- .circleci/config.yml
- .github/workflows/gradle.yml
- appveyor.yml
- interlok-core-apt/src/main/java/com/adaptris/taglet/AbstractTaglet.java
Remove the tag type (in this instance @config) from the JavaDocs.
> Remove the tag type from docs

- interlok-core/src/main/java/com/adaptris/core/http/jetty/BasicJettyConsumer.java
Cherry pick of changes from https://github.com/adaptris/interlok/pull/819
Cherry pick of changes from https://github.com/adaptris/interlok/pull/819
> JETTY: Initialise handlers in init()

- interlok-core/src/test/java/com/adaptris/security/password/SeededAesPbeCryptoTest.java
We can't rely on ./build.gradle to exist under github-actions all the time (it appears) so create a new file using TempFileUtils as the seed.
Use TFU to create a temporary file when we need a seed file. The contents of the file don't matter so it can just default to 'hello world'. 
The file is tracked and deleted when its marker object goes out of scope.
No change for the user
Tests still pass, but a temporary file is used as the seed.
> refactor: use a dynamic seed file

- interlok-core/src/test/java/com/adaptris/security/password/SeededAesPbeCryptoTest.java
A broken password test commented out.
> Commenting out a broken test.

- .github/workflows/codeql-analysis.yml
Improves https://github.com/adaptris/interlok/pull/1089
> Codeql tuning

- interlok-boot/build.gradle
Bump to latest spring boot version
Bump org.springframework.boot:spring-boot-loader to 2.7.11
No vulnerability
Build should pass
> Bump org.springframework.boot:spring-boot-loader to 2.7.11

- interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/FilesystemRetryStore.java
- interlok-core/src/main/java/com/adaptris/core/http/jetty/retry/RetryStore.java
- interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/InMemoryRetryStore.java
- interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryFromJettyTest.java
- interlok-core/src/test/java/com/adaptris/core/http/jetty/retry/RetryStoreTest.java
Updating the interface so the two List methods have default implementations that will throw a UnsupportedOperationException exception if called.
This is to replace having null implementions defined within the classes that don't need them.
RetryStore interface and the classes that implement it.
- [n/a] Added supporting annotations (like @XStreamAlias / @ComponentProfile)
- [n/a] Added DefaultValue annotation when there is a default value (e.g. @DefaultValue('true'))
- [n/a] Added validation annotation (@NotNull...) when required and add @Valid when nested class has some validation
- [n/a] Checked that @NotNull and @NotBlank annotations have a meaningful message when appropriate.
- [n/a] Added comments explaining the …
> Interlok 4134 correct null implementations

- interlok-common/build.gradle
- interlok-core/build.gradle
> bumping jetty version to 10.0.17

- interlok-core/src/main/java/com/adaptris/core/Service.java
- interlok-core/src/main/java/com/adaptris/core/ServiceCollection.java
- interlok-core/src/main/java/com/adaptris/core/ServiceCollectionImp.java
- interlok-core/src/main/java/com/adaptris/core/ServiceImp.java
- interlok-core/src/main/java/com/adaptris/core/SharedServiceImpl.java
- interlok-core/src/test/java/com/adaptris/core/stubs/CheckComponentStateService.java
to enable comments to be added to individual services and shared services.
added the comments to the service interface
if you build this jar and try it in the UI, comments will be available in all services and shared services.
build this jar and try it in the UI, comments will be available in all services and shared services.
> added the config comments to services / shared services

- build.gradle
- interlok-boot/build.gradle
- interlok-core/build.gradle
adding the opens to the release branch
> Interlok 4309 add opens javax management
